local ourMaterials = {}
local actualCount = 0
local prevCount = #list.Get("OverrideMaterials")

local function sanitize(str)
    local sanitized = tostring(str):lower()
    sanitized:gsub("\\", "/")
    if sanitized:sub(1, 1) == "/" then
        sanitized = sanitized:sub(2)
    end

    return sanitized
end

local realms = {
    garrysmod = true,
    cstrike = true,
    tf = true,
    hl2 = true,
    episodic = true,
    ep2 = true,
    csgo = true,
    hl1 = true,
}

local function checkRealms(str)
    local out = {}

    for realm in pairs(realms) do
        if file.Exists("materials/" .. str .. ".vmt", realm) then
            out[#out + 1] = realm
        end
    end

    return out
end

local function list_Add(identifier, item)
    local sanitized = sanitize(item)

    -- ONLY ENABLE IF CLEANING UP
    --[[if ourMaterials[sanitized] then
        local trace = debug.traceback(2, 2)
        local lines = string.Explode("\n", trace)
        local line = lines[3]
        local lineNum = line:match("%:(%d+)%: in main chunk")

        if me then
            lineNum = lineNum - 1
        end

        Msg("[Stools] ") print(Format("Duplicate: %s @ %s", sanitized, lineNum))
    end

    local matRealms = checkRealms(sanitized)
    if #matRealms > 1 then
        Msg("[Stools] ") print(Format("Realms: %s @ %s", sanitized, table.concat(matRealms, ", ")))
    end--]]

    ourMaterials[sanitized] = true
    actualCount = actualCount + 1
    list.Add(identifier, sanitized)
end

----

--DARK METAL/COMBINE
list_Add("OverrideMaterials", "Models/Combine_Turrets/Ceiling_turret/combine_gun003")
list_Add("OverrideMaterials", "Models/Combine_Turrets/Ground_turret/ground_turret01")
list_Add("OverrideMaterials", "Models/Combine_Turrets/Ground_turret/ground_turret02")
list_Add("OverrideMaterials", "Models/props_wasteland/Depot")
list_Add("OverrideMaterials", "Models/props_combine/Combine_Train002")
list_Add("OverrideMaterials", "Models/props_combine/CombineThumper001")
list_Add("OverrideMaterials", "Models/props_combine/CombineThumper002")
list_Add("OverrideMaterials", "Models/Combine_citadel/Combine_Citadel001")
list_Add("OverrideMaterials", "Models/Combine_Dropship/combine_dropship01")
list_Add("OverrideMaterials", "Models/Combine_Helicopter/combine_helicopter01")
list_Add("OverrideMaterials", "Models/Combine_Room/combine_monitor002")
list_Add("OverrideMaterials", "Models/Combine_Scanner/scanner_sheet")
list_Add("OverrideMaterials", "Models/Combine_Camera/combine_camera001")
list_Add("OverrideMaterials", "Models/Items/combine_rifle_cartridge01")
list_Add("OverrideMaterials", "Models/Roller/rollermine_sheet")
list_Add("OverrideMaterials", "models/Roller/rollermine_hacked")
list_Add("OverrideMaterials", "models/Roller/rollermine_splode")
list_Add("OverrideMaterials", "Models/Weapons/W_shotgun/w_shotgun")
list_Add("OverrideMaterials", "Models/Weapons/W_smg1/w_smg2")
list_Add("OverrideMaterials", "Models/Crane_Docks/crane_chair")
list_Add("OverrideMaterials", "models/crashedgunship/crashedgunship")
list_Add("OverrideMaterials", "models/props_combine/ballsocket_sheet")
list_Add("OverrideMaterials", "models/Advisorpod_crash/Advisor_Pod_crash")
list_Add("OverrideMaterials", "models/Advisorpod_crash/Advisor_Pod_crash_02")
list_Add("OverrideMaterials", "models/Combine_Advisor_Pod/combine_advisor_pod")
list_Add("OverrideMaterials", "models/Combine_Helicopter/helicopter_bomb01")
list_Add("OverrideMaterials", "models/Combine_Turrets/combine_cannon_stand02")
list_Add("OverrideMaterials", "models/props_combine/citadeldestroyed001_sheet")
list_Add("OverrideMaterials", "models/props_combine/combine_debris001a")
list_Add("OverrideMaterials", "models/props_combine/combine_hatch01a")
list_Add("OverrideMaterials", "Models/props_combine/breentp_sheet")
list_Add("OverrideMaterials", "Models/props_canal/Canal_Bars003")
list_Add("OverrideMaterials", "Models/props_combine/combine_crane003")
list_Add("OverrideMaterials", "Models/Weapons/V_Stunbaton/W_Shaft01a")
list_Add("OverrideMaterials", "Models/Weapons/W_stunbaton/stunbaton")
list_Add("OverrideMaterials", "Models/props_combine/combine_door01")
list_Add("OverrideMaterials", "models/combine_advisor/mask")
list_Add("OverrideMaterials", "Models/Combine_Advisor/hose")
list_Add("OverrideMaterials", "Models/Combine_Advisor/arm")
list_Add("OverrideMaterials", "Models/Combine_Advisor/camera")
list_Add("OverrideMaterials", "Models/props_combine/Combine_Citadel001")
list_Add("OverrideMaterials", "models/props_combine/citadel_cable")
list_Add("OverrideMaterials", "models/props_combine/citadel_cable_b")
list_Add("OverrideMaterials", "models/props_combine/metal_combinebridge001")
list_Add("OverrideMaterials", "models/gibs/metalgibs/metal_gibs")
list_Add("OverrideMaterials", "models/Combine_Turrets/combine_cannon")

--METAL/RUSTY
list_Add("OverrideMaterials", "models/seesawBridge/metalpipe011a")
list_Add("OverrideMaterials", "models/seesawBridge/metalwall054f")
list_Add("OverrideMaterials", "models/props_silo/pipesa_bombsite")
list_Add("OverrideMaterials", "models/props_silo/de_train_signalbox")
list_Add("OverrideMaterials", "models/props_mining/arches_U")
list_Add("OverrideMaterials", "models/props_mining/ceiling_junk")
list_Add("OverrideMaterials", "models/props_mining/test_model_hdr")
list_Add("OverrideMaterials", "models/props_mining/winch_cable01")
list_Add("OverrideMaterials", "models/props_outland/basementdoor01")
list_Add("OverrideMaterials", "models/props_forest/FurnacePipes01")
list_Add("OverrideMaterials", "models/map1_bridge/metalpipe004a")
list_Add("OverrideMaterials", "models/map1_bridge/metalwall054c")
list_Add("OverrideMaterials", "models/map1_rubble/concretefloor038a")
list_Add("OverrideMaterials", "models/props_c17/canister01a")
list_Add("OverrideMaterials", "models/props_c17/canister02a")
list_Add("OverrideMaterials", "models/props_C17/slidinggate_sheet")
list_Add("OverrideMaterials", "Models/props_trainstation/Trainstation_Arch001")
list_Add("OverrideMaterials", "Models/props_rooftop/RooftopCluster01a")
list_Add("OverrideMaterials", "Models/props_rooftop/SatelliteDish01a")
list_Add("OverrideMaterials", "Models/props_wasteland/bridge-noa")
list_Add("OverrideMaterials", "Models/props_lab/ravendoor_sheet")
list_Add("OverrideMaterials", "models/props_vents/borealis_vent001")
list_Add("OverrideMaterials", "models/props_vents/borealis_vent001b")
list_Add("OverrideMaterials", "models/props_vents/borealis_vent001c")
list_Add("OverrideMaterials", "models/props_pipes/pipemetal001a")
list_Add("OverrideMaterials", "models/props_lab/door_klab01")
list_Add("OverrideMaterials", "models/props_canal/metalwall005b")
list_Add("OverrideMaterials", "models/props_c17/metalladder001")
list_Add("OverrideMaterials", "models/props_c17/metalladder002")
list_Add("OverrideMaterials", "models/props_wasteland/tugboat01")
list_Add("OverrideMaterials", "models/props_wasteland/tugboat02")
list_Add("OverrideMaterials", "models/props_explosive/explosive_butane_can_chunk")
list_Add("OverrideMaterials", "Models/props_trainstation/Trainstation_Ornament001")
list_Add("OverrideMaterials", "Models/props_wasteland/grainelevator01")
list_Add("OverrideMaterials", "models/props_canal/canal_bridge_railing_01a")
list_Add("OverrideMaterials", "models/props_canal/canal_bridge_railing_01b")
list_Add("OverrideMaterials", "models/props_pipes/GutterMetal01a")
list_Add("OverrideMaterials", "models/props_pipes/pipesystem01a_skin2")
list_Add("OverrideMaterials", "models/props_wasteland/quarryobjects01")
list_Add("OverrideMaterials", "models/props_pipes/destroyedpipes01a")
list_Add("OverrideMaterials", "Models/props_pipes/valve001_skin2")
list_Add("OverrideMaterials", "Models/props_junk/i-beam_cluster01")
list_Add("OverrideMaterials", "Models/props_c17/Oil_Drum_Chunks001a")
list_Add("OverrideMaterials", "Models/props_c17/pulley01")
list_Add("OverrideMaterials", "models/props_wasteland/metal_tram001a")
list_Add("OverrideMaterials", "models/combineCannon/ironCmap")
list_Add("OverrideMaterials", "models/map12_building2/roofA_colMap")
list_Add("OverrideMaterials", "models/map12_sawmill/metalwall017a")
list_Add("OverrideMaterials", "models/map12a_hangar/forest_metal_02a_crop")
list_Add("OverrideMaterials", "models/props_2fort/roof_metal001")
list_Add("OverrideMaterials", "models/props_badlands/buildings_rooftop_06")
list_Add("OverrideMaterials", "models/props_farm/metal_fence01")
list_Add("OverrideMaterials", "models/props_mining/dustbowl_roof01")

--METAL OTHER
list_Add("OverrideMaterials", "models/Magnusson_Device/magnusson_device_basecolor")
list_Add("OverrideMaterials", "models/props_C17/powerBox_sheet")
list_Add("OverrideMaterials", "Models/Items/car_battery01")
list_Add("OverrideMaterials", "Models/props_lab/rings_sheet")
list_Add("OverrideMaterials", "models/Alyx/emptool_sheet")
list_Add("OverrideMaterials", "models/weapons/v_grenade/grenade body")
list_Add("OverrideMaterials", "Models/props_vehicles/trailer001a_01")
list_Add("OverrideMaterials", "Models/props_c17/FurnitureBoiler001a")
list_Add("OverrideMaterials", "Models/props_c17/grinderclamp01a")
list_Add("OverrideMaterials", "Models/props_c17/column02a")
list_Add("OverrideMaterials", "Models/props_debris/woodset01")
list_Add("OverrideMaterials", "Models/props_citizen_tech/citizen_trap004")
list_Add("OverrideMaterials", "Models/props_c17/Trap_Crush01a")
list_Add("OverrideMaterials", "Models/props_wasteland/laundry_machines002")
list_Add("OverrideMaterials", "Models/props_buildings/factory_skybox001a")
list_Add("OverrideMaterials", "Models/props_buildings/watertower_001a")
list_Add("OverrideMaterials", "Models/props_buildings/watertower_002a")
list_Add("OverrideMaterials", "Models/props_lab/lockers_sheet")
list_Add("OverrideMaterials", "Models/props_pipes/PipeMetal_cluster01a")
list_Add("OverrideMaterials", "models/props_pipes/pipesystem01a_skin1")
list_Add("OverrideMaterials", "models/props_pipes/pipesystem01a_skin3")
list_Add("OverrideMaterials", "models/props_canal/metalcrate001d")
list_Add("OverrideMaterials", "models/props_debris/metalwall001a")
list_Add("OverrideMaterials", "models/props_combine/combine_moltenplatform01")
list_Add("OverrideMaterials", "models/props_silo/transformer")
list_Add("OverrideMaterials", "models/props_silo/VentilationDuct02")
list_Add("OverrideMaterials", "models/props_2fort/window010")
list_Add("OverrideMaterials", "models/props_2fort/steps_pipes_piece")
list_Add("OverrideMaterials", "models/props_2fort/building_farm01_roof")
list_Add("OverrideMaterials", "models/props_farm/silo_skybox004")
list_Add("OverrideMaterials", "models/props_farm/metal_fence02")
list_Add("OverrideMaterials", "models/props_hydro/observatory_dome")

--PLASTER/BRICK
list_Add("OverrideMaterials", "models/props_building_details/courtyard_template001c_bars")
list_Add("OverrideMaterials", "models/props_c17/furnituremetal001a")
list_Add("OverrideMaterials", "models/props_c17/metalladder003")
list_Add("OverrideMaterials", "models/props_debris/building_template010a")
list_Add("OverrideMaterials", "models/props_canal/canal_bridge_railing_01c")
list_Add("OverrideMaterials", "models/props_debris/plasterceiling008a")
list_Add("OverrideMaterials", "models/props_debris/plasterwall034a")
list_Add("OverrideMaterials", "models/props_debris/building_template022j")
list_Add("OverrideMaterials", "models/props_debris/plasterwall034d")
list_Add("OverrideMaterials", "models/props_debris/plasterwall039c")
list_Add("OverrideMaterials", "models/props_debris/plasterwall040c")
list_Add("OverrideMaterials", "models/props_animated_breakable/smokestack/brickwall002a")
list_Add("OverrideMaterials", "models/props_debris/concretewall019a")
list_Add("OverrideMaterials", "Models/props_animated_breakable/Smokestack/brick_chimney01")
list_Add("OverrideMaterials", "models/props_debris/tilefloor001c")
list_Add("OverrideMaterials", "models/props_silo/prodwlla")
list_Add("OverrideMaterials", "models/hybridPhysx/unlitRubbleTexture")
list_Add("OverrideMaterials", "models/props_badlands/computerwall")

--CONCRETE
list_Add("OverrideMaterials", "Models/props_debris/concretedebris_chunk01")
list_Add("OverrideMaterials", "Models/props_c17/overpass_001a")
list_Add("OverrideMaterials", "models/props_buildings/destroyedbuilldingwall01a")
list_Add("OverrideMaterials", "models/props_buildings/plasterwall021a")
list_Add("OverrideMaterials", "models/props_wasteland/concretefloor010a")
list_Add("OverrideMaterials", "models/props_wasteland/concretewall064b")
list_Add("OverrideMaterials", "models/props_wasteland/concretewall066a")
list_Add("OverrideMaterials", "models/props_debris/composite_debris")
list_Add("OverrideMaterials", "models/props_debris/concretefloor013a")
list_Add("OverrideMaterials", "models/props_debris/plasterwall009d")
list_Add("OverrideMaterials", "models/props_debris/plasterwall021a")
list_Add("OverrideMaterials", "models/props_debris/concretefloor020a")
list_Add("OverrideMaterials", "models/seesawBridge/bridge_concrete")
list_Add("OverrideMaterials", "models/hybridPhysx/concreteCylBaked")

--ROCK
list_Add("OverrideMaterials", "models/props_wasteland/dirtwall001a")
list_Add("OverrideMaterials", "Models/props_skybox/coast01_sheet")
list_Add("OverrideMaterials", "models/props_canal/rock_riverbed01a")
list_Add("OverrideMaterials", "models/props_wasteland/rockcliff02a")
list_Add("OverrideMaterials", "models/props_wasteland/rockcliff02b")
list_Add("OverrideMaterials", "models/props_wasteland/rockcliff02c")
list_Add("OverrideMaterials", "models/props_wasteland/rockcliff04a")
list_Add("OverrideMaterials", "models/props_wasteland/rockgranite02a")
list_Add("OverrideMaterials", "models/Cliffs/Cliff01")
list_Add("OverrideMaterials", "models/Cliffs/Cliff02")
list_Add("OverrideMaterials", "models/Cliffs/cliff_path01")
list_Add("OverrideMaterials", "models/Cliffs/Rocks01")
list_Add("OverrideMaterials", "models/Cliffs/Rocks02")
list_Add("OverrideMaterials", "models/props_foliage/Coastrock02")
list_Add("OverrideMaterials", "models/props_foliage/forestrock01")
list_Add("OverrideMaterials", "models/props_foliage/forestrock_single01")
list_Add("OverrideMaterials", "models/props_foliage/Rocks01")
list_Add("OverrideMaterials", "models/props_trainstation/train_orecar_ore")
list_Add("OverrideMaterials", "models/props_badlands/rockground001")
list_Add("OverrideMaterials", "models/props_forest/rock006")
list_Add("OverrideMaterials", "models/props_forest/cliff_detail")
list_Add("OverrideMaterials", "models/props_mining/gravel_pile001")
list_Add("OverrideMaterials", "models/props_nature/rock_worn001")

--WOOD
list_Add("OverrideMaterials", "models/props_foliage/oak_tree01")
list_Add("OverrideMaterials", "models/props_foliage/driftwood_01a")
list_Add("OverrideMaterials", "Models/props_junk/ravenholmsign_sheet")
list_Add("OverrideMaterials", "Models/Gibs/furniture_gibs/FurnitureWoodDrawers001a")
list_Add("OverrideMaterials", "Models/props_interiors/furniture_shelf01a")
list_Add("OverrideMaterials", "Models/props_docks/dock02a")
list_Add("OverrideMaterials", "models/gibs/woodgibs/woodgibs01")
list_Add("OverrideMaterials", "models/gibs/woodgibs/woodgibs02")
list_Add("OverrideMaterials", "models/gibs/woodgibs/woodgibs03")
list_Add("OverrideMaterials", "Models/props_docks/canal_docks01a")
list_Add("OverrideMaterials", "models/props_wasteland/wood_fence01a")
list_Add("OverrideMaterials", "models/props_wasteland/wood_fence01a_skin2")
list_Add("OverrideMaterials", "models/advisorBarn/woodfloor005a")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection16-roofX")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection17-roofY")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection2-wallCornerZXneg")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection2-wallCornerZXPos")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection2-wallXDOWN")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection2-wallXUP")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection2-wallZDOWN")
list_Add("OverrideMaterials", "models/ep2_out12_hut1/projection5-porchXUP")
list_Add("OverrideMaterials", "models/map10_doors/doubleDoorColourMap")
list_Add("OverrideMaterials", "models/map10_doors/singleDoorColourMap")
list_Add("OverrideMaterials", "models/map12_building2/woodwall043a")
list_Add("OverrideMaterials", "models/map12_building2/woodwall048d")
list_Add("OverrideMaterials", "models/map12_sawmill/projection1-frontCS")
list_Add("OverrideMaterials", "models/map12_sawmill/projection2-top2CS")
list_Add("OverrideMaterials", "models/map1_boards/woodfloor008a")
list_Add("OverrideMaterials", "models/props_forest/dog_gate")
list_Add("OverrideMaterials", "models/props_forest/fence_border")
list_Add("OverrideMaterials", "models/props_junk/wood_spool01")
list_Add("OverrideMaterials", "models/props_badlands/temptile")
list_Add("OverrideMaterials", "models/props_badlands/buildings_walls005b")
list_Add("OverrideMaterials", "models/props_badlands/buildings_redwood_walls01")
list_Add("OverrideMaterials", "models/props_badlands/buildings_floor001")
list_Add("OverrideMaterials", "models/props_farm/tree_trunk001")
list_Add("OverrideMaterials", "models/props_farm/silo_skybox003")
list_Add("OverrideMaterials", "models/props_farm/rafters001")
list_Add("OverrideMaterials", "models/props_forest/sawmill_wood")
list_Add("OverrideMaterials", "models/props_mining/wooden_rail01")

--FABRIC
list_Add("OverrideMaterials", "Models/props_c17/FurnitureMattress001a")
list_Add("OverrideMaterials", "Models/props_c17/FurnitureMattress002a")
list_Add("OverrideMaterials", "models/props_c17/furniturefabric001a")
list_Add("OverrideMaterials", "models/props_c17/furniturefabric002a")
list_Add("OverrideMaterials", "models/props_c17/furniturefabric003a")

--MAPS/PAPER
list_Add("OverrideMaterials", "models/props_canal/coastmap_sheet")
list_Add("OverrideMaterials", "models/props_c17/paper01")
list_Add("OverrideMaterials", "models/props_canal/canalmap_sheet")
list_Add("OverrideMaterials", "effects/borealis_filmslide_001")
list_Add("OverrideMaterials", "effects/borealis_image_001")
list_Add("OverrideMaterials", "effects/borealis_plans_01")
list_Add("OverrideMaterials", "effects/borealis_plans_02")
list_Add("OverrideMaterials", "effects/borealis_plans_03")
list_Add("OverrideMaterials", "effects/borealis_schematic_001")
list_Add("OverrideMaterials", "models/props_lab/clipboard_sheet")
list_Add("OverrideMaterials", "models/props_outland/strider_sign")
list_Add("OverrideMaterials", "models/buildables/dispenser/disp_blueprint_build")
list_Add("OverrideMaterials", "models/buildables/sentry1/blueprint_build")
list_Add("OverrideMaterials", "models/buildables/teleporter/teleporter_blueprint_enter")
list_Add("OverrideMaterials", "models/buildables/teleporter/teleporter_blueprint_exit")
list_Add("OverrideMaterials", "models/buildables/teleporter/teleporter_blueprint_model")
list_Add("OverrideMaterials", "models/props_hydro/wall_map")
list_Add("OverrideMaterials", "models/props_movies/alert_sign/alert_sign_red")
list_Add("OverrideMaterials", "models/props_movies/alert_sign/alert_sign_blue")
list_Add("OverrideMaterials", "models/weapons/v_baseball/baseball_sheet")

--FENCE/GRATE
list_Add("OverrideMaterials", "models/props_c17/gate_door02a")
list_Add("OverrideMaterials", "Models/props_c17/fence_alpha")
list_Add("OverrideMaterials", "Models/props_c17/metaltruss012b")
list_Add("OverrideMaterials", "models/props_interiors/metalfence007a")
list_Add("OverrideMaterials", "Models/props_lab/teleportgate_fence")
list_Add("OverrideMaterials", "models/props_junk/plasticcrate01a")
list_Add("OverrideMaterials", "models/props_junk/plasticcrate01b")
list_Add("OverrideMaterials", "models/props_junk/plasticcrate01c")
list_Add("OverrideMaterials", "models/props_junk/plasticcrate01d")
list_Add("OverrideMaterials", "models/props_junk/plasticcrate01e")
list_Add("OverrideMaterials", "models/props_forest/dog_gate_fence")
list_Add("OverrideMaterials", "models/props_forest/fence_chicken_alpha")
list_Add("OverrideMaterials", "models/Cliffs/ferns01")
list_Add("OverrideMaterials", "models/props_foliage/tree_deciduous_01a_branches")
list_Add("OverrideMaterials", "models/props_foliage/Tree_dry02")
list_Add("OverrideMaterials", "models/props_foliage/vines01")
list_Add("OverrideMaterials", "models/props_forest/FenceBarbedWire_Wire")
list_Add("OverrideMaterials", "models/props_forest/FenceBarbedWire_Wire2")

--BRIGHT AND NOISY
list_Add("OverrideMaterials", "models/props_silo/wall_console1")
list_Add("OverrideMaterials", "models/props_silo/desk_console1")
list_Add("OverrideMaterials", "models/props_silo/rocket_body")
list_Add("OverrideMaterials", "Models/props_junk/TrafficCone001a")
list_Add("OverrideMaterials", "Models/props_lab/hevcharger_faceplate")
list_Add("OverrideMaterials", "Models/props_interiors/SodaMachine01a")
list_Add("OverrideMaterials", "Models/props_c17/clock01")
list_Add("OverrideMaterials", "Models/Weapons/v_crossbow/rebar")
list_Add("OverrideMaterials", "Models/Weapons/v_crossbow/string")
list_Add("OverrideMaterials", "Models/props_rooftop/Letter_Sign001")
list_Add("OverrideMaterials", "Models/props_rooftop/Letter_Sign001b")
list_Add("OverrideMaterials", "Models/props_rooftop/Letter_Sign002")
list_Add("OverrideMaterials", "Models/props_pipes/valve003_skin1")
list_Add("OverrideMaterials", "Models/props_c17/floodlighthousing")
list_Add("OverrideMaterials", "Models/props_borealis/windlass01")
list_Add("OverrideMaterials", "Models/props_borealis/mooring_cleat001")
list_Add("OverrideMaterials", "Models/props_c17/chairfab01")
list_Add("OverrideMaterials", "Models/props_junk/pot_objects01")
list_Add("OverrideMaterials", "models/weapons/v_crossbow/rebar_glow")
list_Add("OverrideMaterials", "models/antlion/antlion_innards")
list_Add("OverrideMaterials", "models/worldcraft/nodes/air_node_hint")
list_Add("OverrideMaterials", "Models/Worldcraft/axis_helper/axis_helper")
list_Add("OverrideMaterials", "Models/Worldcraft/Nodes/Node_hint")
list_Add("OverrideMaterials", "Models/props_combine/breenconsole_sheet")
list_Add("OverrideMaterials", "Models/Weapons/V_IRifle/V_IRifle_core")
list_Add("OverrideMaterials", "models/combine_scanner/scanner_eye")
list_Add("OverrideMaterials", "models/Alyx/eyeball_l")
list_Add("OverrideMaterials", "models/extras/crank_sheet")
list_Add("OverrideMaterials", "models/extras/widget_sheet")
list_Add("OverrideMaterials", "models/extras/speech_info")
list_Add("OverrideMaterials", "models/extras/speech_info_used")
list_Add("OverrideMaterials", "models/props_junk/flare")
list_Add("OverrideMaterials", "models/props_junk/flare_burnt")
list_Add("OverrideMaterials", "models/props_forest/whiteforestinn_sign")
list_Add("OverrideMaterials", "models/props_forest/whiteForestSign")
list_Add("OverrideMaterials", "models/props_junk/gnome")
list_Add("OverrideMaterials", "models/props_silo/pylon")
list_Add("OverrideMaterials", "models/Spitball/spitball")
list_Add("OverrideMaterials", "models/weapons/c_items/c_sandwich")
list_Add("OverrideMaterials", "models/class_menu/random_class_icon_red")
list_Add("OverrideMaterials", "models/class_menu/random_class_icon_blue")
list_Add("OverrideMaterials", "models/effects/smiley")
list_Add("OverrideMaterials", "models/effects/partyhat_blue")
list_Add("OverrideMaterials", "models/effects/partyhat")
list_Add("OverrideMaterials", "models/effects/cappoint_logo_red_R")
list_Add("OverrideMaterials", "models/effects/cappoint_logo_red_g")
list_Add("OverrideMaterials", "models/effects/cappoint_logo_red_b")
list_Add("OverrideMaterials", "models/effects/pyro/pilotlight_motion")
list_Add("OverrideMaterials", "models/effects/muzzleflash/brightmuzzle")
list_Add("OverrideMaterials", "models/props_mining/track_lighting_red")
list_Add("OverrideMaterials", "models/props_mining/track_lighting_blue")
list_Add("OverrideMaterials", "models/props_farm/haypile001")

--TRANSPARENCIES
list_Add("OverrideMaterials", "models/props_combine/prtl_sky_sheet")
list_Add("OverrideMaterials", "models/effects/splode1_sheet")
list_Add("OverrideMaterials", "models/effects/splodearc_sheet")
list_Add("OverrideMaterials", "models/effects/splode_sheet")
list_Add("OverrideMaterials", "models/shadertest/shader3_dudv")
list_Add("OverrideMaterials", "models/barnacle/roots")
list_Add("OverrideMaterials", "models/roller/rollermine_glow")
list_Add("OverrideMaterials", "models/props_c17/bladeblur")
list_Add("OverrideMaterials", "models/airboat/airboat_blur02")
list_Add("OverrideMaterials", "models/effects/comball_glow1")
list_Add("OverrideMaterials", "models/effects/comball_glow2")
list_Add("OverrideMaterials", "models/effects/portalrift_sheet")
list_Add("OverrideMaterials", "models/weapons/v_smg1/texture5")
list_Add("OverrideMaterials", "models/weapons/w_smg1/smg_crosshair")
list_Add("OverrideMaterials", "models/error/new light1")
list_Add("OverrideMaterials", "models/weapons/v_slam/new light2")
list_Add("OverrideMaterials", "models/Alyx/hairbits")
list_Add("OverrideMaterials", "models/Effects/splodecard1_sheet")
list_Add("OverrideMaterials", "models/Effects/splodecard2_sheet")
list_Add("OverrideMaterials", "models/Effects/splodecard3_sheet")
list_Add("OverrideMaterials", "models/props_C17/powerbox_wires")
list_Add("OverrideMaterials", "models/props_combine/cit_cloud001")
list_Add("OverrideMaterials", "models/props_combine/cit_cloud002")
list_Add("OverrideMaterials", "models/props_combine/cit_cloud003")
list_Add("OverrideMaterials", "models/props_combine/cit_corebright")
list_Add("OverrideMaterials", "models/props_combine/citadelcard")
list_Add("OverrideMaterials", "models/Roller/rollermine_gloworange")
list_Add("OverrideMaterials", "models/Roller/rollermine_glowred")
list_Add("OverrideMaterials", "Effects/fake_fog01")
list_Add("OverrideMaterials", "Effects/fake_fog02")
list_Add("OverrideMaterials", "Effects/fake_fog03")
list_Add("OverrideMaterials", "Effects/cloud_funnel_01")
list_Add("OverrideMaterials", "Effects/building_card01")
list_Add("OverrideMaterials", "effects/citadel_destroyed_card_02a")
list_Add("OverrideMaterials", "effects/citadel_sky_card_01")
list_Add("OverrideMaterials", "models/Magnusson/magnusson_hair")
list_Add("OverrideMaterials", "models/props_farm/tree_leaves001")
list_Add("OverrideMaterials", "models/props_farm/tree_branches001")
list_Add("OverrideMaterials", "models/props_farm/haypile001_card")
list_Add("OverrideMaterials", "models/props_nucleus/MP_energy")
list_Add("OverrideMaterials", "models/effects/invulnerability/invulnerability_red")
list_Add("OverrideMaterials", "models/effects/invulnerability/invulnerability_blue")
list_Add("OverrideMaterials", "models/weapons/c_items/c_urinejar_urine")

--INTERFACE
list_Add("OverrideMaterials", "models/props_combine/combine_interface_disp")
list_Add("OverrideMaterials", "models/props_combine/combine_monitorbay_disp")
list_Add("OverrideMaterials", "Models/props_combine/combine_intmonitor001_disp")
list_Add("OverrideMaterials", "Models/props_combine/introomarea_disp")
list_Add("OverrideMaterials", "Models/props_combine/masterinterface01c")
list_Add("OverrideMaterials", "Models/props_combine/masterinterface_alert")
list_Add("OverrideMaterials", "Models/props_combine/masterinterface_disp")
list_Add("OverrideMaterials", "Models/props_combine/tpcontroller_disp")
list_Add("OverrideMaterials", "models/props_combine/combine_intmonitor001_disp_alert")
list_Add("OverrideMaterials", "models/props_combine/combine_intmonitor001_disp_off")
list_Add("OverrideMaterials", "Effects/combinedisplay_mossmanrec")
list_Add("OverrideMaterials", "Effects/combinedisplay_mossman1")
list_Add("OverrideMaterials", "Effects/combinedisplay_gna")
list_Add("OverrideMaterials", "Effects/combinedisplay_eli")
list_Add("OverrideMaterials", "Effects/combinedisplay_dump")
list_Add("OverrideMaterials", "Effects/combinedisplay_core_")
list_Add("OverrideMaterials", "models/props_lab/security_screens")
list_Add("OverrideMaterials", "models/props_lab/security_screens2")
list_Add("OverrideMaterials", "Models/props_lab/computer_disp")
list_Add("OverrideMaterials", "Models/props_lab/eyescanner_disp")
list_Add("OverrideMaterials", "Models/props_lab/servers_disp")
list_Add("OverrideMaterials", "Models/props_lab/printout_sheet")
list_Add("OverrideMaterials", "effects/advisorMonitorDisplay")
list_Add("OverrideMaterials", "effects/minescreen_static01_")
list_Add("OverrideMaterials", "effects/screen_monitor_blank")
list_Add("OverrideMaterials", "effects/silodisplay_forestcams_001")
list_Add("OverrideMaterials", "effects/silodisplay_forestcams_002")
list_Add("OverrideMaterials", "effects/whiteforest_screen")
list_Add("OverrideMaterials", "models/props_lab/generatorconsole_disp")
list_Add("OverrideMaterials", "models/props_silo/launchRoomDisplayA")
list_Add("OverrideMaterials", "models/props_silo/launchRoomDisplayB")
list_Add("OverrideMaterials", "models/props_silo/launchRoomDisplayC")
list_Add("OverrideMaterials", "models/props_silo/launchRoomDisplayD")
list_Add("OverrideMaterials", "models/props_silo/launchRoomDisplayOff")
list_Add("OverrideMaterials", "models/props_silo/rocket_countdown_1")
list_Add("OverrideMaterials", "models/props_silo/rocket_countdown_zero")
list_Add("OverrideMaterials", "models/buildables/sentry1/sentry_pulse3")
list_Add("OverrideMaterials", "models/buildables/sentry1/sentry_pulse_blue")
list_Add("OverrideMaterials", "models/buildables/sentry1/sentry_pulse")
list_Add("OverrideMaterials", "models/buildables/dispenser/dispenser_upgrades_animated")
list_Add("OverrideMaterials", "models/vgui/tv_spectate_on")
list_Add("OverrideMaterials", "models/vgui/tv_spectate")
list_Add("OverrideMaterials", "models/vgui/filmscreen_dark")

--GLASS
list_Add("OverrideMaterials", "models/props_combine/health_charger_glass")
list_Add("OverrideMaterials", "models/props_c17/fisheyelens_dx60")
list_Add("OverrideMaterials", "models/dog/eyeglass")
list_Add("OverrideMaterials", "Models/props_trainstation/Trainstation_Clock_Glass001")
list_Add("OverrideMaterials", "Models/props_lab/suitcase_glass")
list_Add("OverrideMaterials", "Models/props_lab/airlock_laser")
list_Add("OverrideMaterials", "Models/props_lab/crematorcase_jar")
list_Add("OverrideMaterials", "models/props_combine/pipes01")
list_Add("OverrideMaterials", "models/props_silo/light_red1_glass")
list_Add("OverrideMaterials", "models/buildables/spawn_room/turret_mount_glass")
list_Add("OverrideMaterials", "models/props_2fort/window_glass004")
list_Add("OverrideMaterials", "models/props_badlands/glass_silo")
list_Add("OverrideMaterials", "models/props_mining/window_industrial01_glass01_skin2")
list_Add("OverrideMaterials", "models/props_mining/window_industrial01_glass01")
list_Add("OverrideMaterials", "models/props_spytech/wall_clock_glass")

--SHADER
list_Add("OverrideMaterials", "models/shadertest/predator")
list_Add("OverrideMaterials", "models/effects/slimebubble_sheet")
list_Add("OverrideMaterials", "models/props_lab/cornerunit_cloud")
list_Add("OverrideMaterials", "models/props_lab/warp_sheet")
list_Add("OverrideMaterials", "models/alyx/emptool_glow")
list_Add("OverrideMaterials", "models/props_combine/stasisfield_beam")
list_Add("OverrideMaterials", "models/props_lab/xencrystal_sheet")
list_Add("OverrideMaterials", "Models/props_lab/monitorface")
list_Add("OverrideMaterials", "models/props_combine/cit_beacon")
list_Add("OverrideMaterials", "models/props_combine/cit_splode1")
list_Add("OverrideMaterials", "models/props_lab/projector_noise")
list_Add("OverrideMaterials", "effects/binary_noise_B_01")
list_Add("OverrideMaterials", "effects/binary_noise_G_01")
list_Add("OverrideMaterials", "effects/binary_noise_R_01")
list_Add("OverrideMaterials", "models/Debug/debugmesh")
list_Add("OverrideMaterials", "models/effects/vol_lightmask02")
list_Add("OverrideMaterials", "models/Magnusson_Device/magnusson_device_glow")
list_Add("OverrideMaterials", "models/Magnusson_Teleporter/magnusson_teleporter_fxglow1")
list_Add("OverrideMaterials", "models/Magnusson_Teleporter/magnusson_teleporter_fxglow_off")
list_Add("OverrideMaterials", "models/props_combine/sphere")
list_Add("OverrideMaterials", "models/props_hive/larval_essence/larval_essence")
list_Add("OverrideMaterials", "models/props_forest/waterfall001")
list_Add("OverrideMaterials", "models/props_badlands/beam")
list_Add("OverrideMaterials", "models/effects/muzzleflash/blurmuzzle")
list_Add("OverrideMaterials", "models/effects/cappoint_beam_blue")
list_Add("OverrideMaterials", "models/effects/pyro/pilotlight")
list_Add("OverrideMaterials", "models/effects/cappoint_beam_red")
list_Add("OverrideMaterials", "models/effects/cappoint_beam_neutral")

--ORGANIC
list_Add("OverrideMaterials", "models/weapons/v_crowbar/crowbar_cyl")
list_Add("OverrideMaterials", "models/flesh")
list_Add("OverrideMaterials", "models/Stalker/stalker_teeth")
list_Add("OverrideMaterials", "models/vortigaunt/vortigaunt_blue")
list_Add("OverrideMaterials", "models/AntLion/antlion_worker_wing")
list_Add("OverrideMaterials", "models/antlion_grub/Antlion_grub")
list_Add("OverrideMaterials", "models/antlion_grub/Antlion_grub_squashed")
list_Add("OverrideMaterials", "models/Combine_advisor_juvenile/Combine_advisor_juvenile")
list_Add("OverrideMaterials", "models/combine_strider/interior_bits")
list_Add("OverrideMaterials", "models/combine_strider/strider_brain")
list_Add("OverrideMaterials", "models/grub_nugget/grub_nugget")
list_Add("OverrideMaterials", "models/props_hive/webSackFull")
list_Add("OverrideMaterials", "models/props_hive/webSackHalf")
list_Add("OverrideMaterials", "models/props_hive/webSackHalf_cool")
list_Add("OverrideMaterials", "models/props_hive/webSackHalf_dead")
list_Add("OverrideMaterials", "models/Ministrider/mini_armor_basecolor")

--BONES
list_Add("OverrideMaterials", "Models/Gibs/HGibs/spine")
list_Add("OverrideMaterials", "Models/Gibs/HGibs/Skull1")
list_Add("OverrideMaterials", "Models/Gibs/HGibs/scapula")
list_Add("OverrideMaterials", "Models/Gibs/HGibs/rib")
list_Add("OverrideMaterials", "models/skeleton/skeleton")
list_Add("OverrideMaterials", "models/skeleton/skeleton_bloody")
list_Add("OverrideMaterials", "models/skeleton/skeleton_bleached")
list_Add("OverrideMaterials", "models/skeleton/skeleton_decomp")

--Combine
list_Add("OverrideMaterials", "effects/com_shield002a")
list_Add("OverrideMaterials", "effects/com_shield003a")
list_Add("OverrideMaterials", "effects/com_shield004a")
list_Add("OverrideMaterials", "effects/combine_binocoverlay")
list_Add("OverrideMaterials", "effects/prisonmap_disp")
list_Add("OverrideMaterials", "effects/tvscreen_noise001a")
list_Add("OverrideMaterials", "effects/tvscreen_noise002a")

--HL2
list_Add("OverrideMaterials", "models/editor/overlay_helper")
list_Add("OverrideMaterials", "models/editor/scripted_sequence")
list_Add("OverrideMaterials", "models/player/player_chrome1")
list_Add("OverrideMaterials", "models/props_borealis/meathook01")
list_Add("OverrideMaterials", "models/props_buildings/collapsedbuilding02a")
list_Add("OverrideMaterials", "models/props_buildings/destroyedbuillding01a")
list_Add("OverrideMaterials", "models/props_c17/concretewall020a")
list_Add("OverrideMaterials", "models/props_c17/gasmeters001a")
list_Add("OverrideMaterials", "models/props_c17/overhangcluster01a")
list_Add("OverrideMaterials", "models/props_interiors/radiator01a")
list_Add("OverrideMaterials", "models/props_interiors/handrail02a")
list_Add("OverrideMaterials", "models/props_junk/popcan01a")
list_Add("OverrideMaterials", "models/props_junk/popcan02a")
list_Add("OverrideMaterials", "models/props_junk/popcan03a")
list_Add("OverrideMaterials", "models/props_junk/cardboard_boxes001a")
list_Add("OverrideMaterials", "models/props_junk/propanecanister01a")
list_Add("OverrideMaterials", "models/props_junk/propanecanister01b")
list_Add("OverrideMaterials", "models/props_junk/trashdumpster01a")
list_Add("OverrideMaterials", "models/props_junk/wood_palletcrate001a")
list_Add("OverrideMaterials", "models/props_junk/woodcrates01a")
list_Add("OverrideMaterials", "models/props_junk/woodcrates02a")
list_Add("OverrideMaterials", "models/props_lab/chess_sheet")
list_Add("OverrideMaterials", "models/props_lab/handrail01_exterior_system")
list_Add("OverrideMaterials", "models/props_lab/lab_hose001")
list_Add("OverrideMaterials", "models/props_lab/keypad_sheet")
list_Add("OverrideMaterials", "models/props_lab/keypad_granted")
list_Add("OverrideMaterials", "models/props_lab/keypad_denied")
list_Add("OverrideMaterials", "models/props_trainstation/traintrack001a")
list_Add("OverrideMaterials", "models/props_wasteland/cargo_container01")
list_Add("OverrideMaterials", "models/props_wasteland/cargo_container02")
list_Add("OverrideMaterials", "models/props_wasteland/cargo_container03")

--EP1/2 Extended
list_Add("OverrideMaterials", "models/props_combine/core_sheet")
list_Add("OverrideMaterials", "models/props_combine/coredx70")
list_Add("OverrideMaterials", "models/props_combine/combine_hatch01a_glass")
list_Add("OverrideMaterials", "models/props_trainstation/trainstation_roofdebris01")
list_Add("OverrideMaterials", "dev/dev_energyflow")
list_Add("OverrideMaterials", "models/advisorbarn/colmap-slatroofb")
list_Add("OverrideMaterials", "models/citadeldestruction/citadel_metalwall063a")
list_Add("OverrideMaterials", "models/map12_bigbaddaboom/concretefloor_bunker02b")
list_Add("OverrideMaterials", "models/map12_bigbaddaboom/rocks01")
list_Add("OverrideMaterials", "models/map12_building2/roofporch_colmap")
list_Add("OverrideMaterials", "models/map12a_hangar/metalwall017a")
list_Add("OverrideMaterials", "models/map12a_hangar/glasswindow005c")
list_Add("OverrideMaterials", "models/map12a_hangar/metalwall030a")
list_Add("OverrideMaterials", "models/props_combine/sphere_dx8")
list_Add("OverrideMaterials", "models/props_dev/test_graygrid")
list_Add("OverrideMaterials", "models/props_foliage/rockwall011d")
list_Add("OverrideMaterials", "models/props_lab/power_cable001")
list_Add("OverrideMaterials", "models/props_mining/stalactite_rock01")
list_Add("OverrideMaterials", "models/props_mining/warehouse_ceiling01")
list_Add("OverrideMaterials", "models/props_radiostation/metal_truss")
list_Add("OverrideMaterials", "models/props_wasteland/rocks02a")
list_Add("OverrideMaterials", "models/rockslide/forestrock01")
list_Add("OverrideMaterials", "models/rockslide/rockcliff02a")
list_Add("OverrideMaterials", "models/rockslide/rocks01")
list_Add("OverrideMaterials", "models/seesawbridge/concretefloor037b")
list_Add("OverrideMaterials", "models/seesawbridge/concretewall_mine_002c")
list_Add("OverrideMaterials", "models/seesawbridge/metalpipe002a")
list_Add("OverrideMaterials", "models/seesawbridge/metalpipe003a")
list_Add("OverrideMaterials", "models/seesawbridge/metalpipe010a")
list_Add("OverrideMaterials", "models/seesawbridge/metaltruss022a")
list_Add("OverrideMaterials", "models/seesawbridge/metaltruss024a")
list_Add("OverrideMaterials", "models/striderbustervendor1/colmapz-wallsection_8")
list_Add("OverrideMaterials", "models/striderbustervendor1/colmapz-wallsection_6")
list_Add("OverrideMaterials", "models/striderbustervendor1/colmapz-wallsection_3")
list_Add("OverrideMaterials", "models/striderbustervendor1/woodwall043a")
list_Add("OverrideMaterials", "models/striderbustervendor1/colmapx-wallsection_5")
list_Add("OverrideMaterials", "models/striderbustervendor1/colmapx-wallsection_4")
list_Add("OverrideMaterials", "vgui/screens/radar")
list_Add("OverrideMaterials", "vgui/screens/vgui_overlay")
list_Add("OverrideMaterials", "models/props_mining/diesel_generator_panel")
list_Add("OverrideMaterials", "effects/fire_glow")
list_Add("OverrideMaterials", "effects/fake_smoke01")
list_Add("OverrideMaterials", "effects/magmonitor_idle")
list_Add("OverrideMaterials", "effects/magmonitor_talk")
list_Add("OverrideMaterials", "effects/gman_silouette_01")
list_Add("OverrideMaterials", "glass/glasswindow_refract01")

--CS:S
list_Add("OverrideMaterials", "models/cs_havana/wndc")
list_Add("OverrideMaterials", "models/cs_havana/wndd")
list_Add("OverrideMaterials", "models/cs_havana/wndx1")
list_Add("OverrideMaterials", "models/cs_havana/wndl")
list_Add("OverrideMaterials", "models/de_dust/dustteeth")
list_Add("OverrideMaterials", "models/de_dust/crates/crate_128x128")
list_Add("OverrideMaterials", "models/de_dust/crates/crate_64x64")
list_Add("OverrideMaterials", "models/de_dust/crates/crate_64x64g")
list_Add("OverrideMaterials", "models/de_dust/crates/crate_64x64h")
list_Add("OverrideMaterials", "models/pi_window/plaster")
list_Add("OverrideMaterials", "models/player/ct_gign/ct_gign_glass")
list_Add("OverrideMaterials", "models/props/cs_assault/water_tower2")
list_Add("OverrideMaterials", "models/props/cs_office/screenb")
list_Add("OverrideMaterials", "models/props/cs_office/poster_backing")
list_Add("OverrideMaterials", "models/props/de_inferno/breakablewindowglass")
list_Add("OverrideMaterials", "models/props/de_inferno/cactus")
list_Add("OverrideMaterials", "models/props/de_inferno/clayoven2")
list_Add("OverrideMaterials", "models/props/de_inferno/infplasterwall044b")
list_Add("OverrideMaterials", "models/props/de_inferno/claypot03")
list_Add("OverrideMaterials", "models/props/de_inferno/pillar")
list_Add("OverrideMaterials", "models/props/de_inferno/pillarb")
list_Add("OverrideMaterials", "models/props/de_inferno/pillarred")
list_Add("OverrideMaterials", "models/props/de_inferno/pillarsa")
list_Add("OverrideMaterials", "models/props/de_nuke/light_red1_glass")
list_Add("OverrideMaterials", "models/props/de_nuke/light_red1_glass_on")
list_Add("OverrideMaterials", "models/props/de_nuke/light_yellow1_glass")
list_Add("OverrideMaterials", "models/props/de_nuke/light_yellow1_glass_on")
list_Add("OverrideMaterials", "models/props/de_nuke/nukibeama")
list_Add("OverrideMaterials", "models/props/de_nuke/nukibeamadirty")
list_Add("OverrideMaterials", "models/props/de_nuke/nuklogo")
list_Add("OverrideMaterials", "models/props/de_nuke/pipesa_bombsite")
list_Add("OverrideMaterials", "models/props/de_nuke/pipeset_metal02")
list_Add("OverrideMaterials", "models/props/de_nuke/concretefloor008a")
list_Add("OverrideMaterials", "models/props/de_nuke/crane_walkway")
list_Add("OverrideMaterials", "models/props/de_nuke/crate")
list_Add("OverrideMaterials", "models/props/de_nuke/containmentbuildingrailing01")
list_Add("OverrideMaterials", "models/props/de_nuke/storagetank2")
list_Add("OverrideMaterials", "models/props/de_nuke/railing_ramp_a")
list_Add("OverrideMaterials", "models/props/de_nuke/railing_tunnels")
list_Add("OverrideMaterials", "models/props/de_port/cargo_container01")
list_Add("OverrideMaterials", "models/props/de_port/cargo_container02")
list_Add("OverrideMaterials", "models/props/de_port/cargo_container03")
list_Add("OverrideMaterials", "models/props/de_port/metalwall083b")
list_Add("OverrideMaterials", "models/props/de_port/tankoil1b")
list_Add("OverrideMaterials", "models/props/de_port/clouds")
list_Add("OverrideMaterials", "models/props/de_prodigy/traintrack001a")
list_Add("OverrideMaterials", "models/props/de_prodigy/prodwlla")
list_Add("OverrideMaterials", "models/props/de_train/train_gutterandpipes")
list_Add("OverrideMaterials", "models/props_c17/metalwall085a")
list_Add("OverrideMaterials", "models/props/de_nuke/pipeset_metal")
list_Add("OverrideMaterials", "cs_havana/metalfence007a")
list_Add("OverrideMaterials", "de_nuke/nukskylighta")
list_Add("OverrideMaterials", "environment maps/pipemetal001a")
list_Add("OverrideMaterials", "environment maps/pipemetal004a")
list_Add("OverrideMaterials", "environment maps/pipemetal004b")
list_Add("OverrideMaterials", "environment maps/pipeset_metal")
list_Add("OverrideMaterials", "models/props/cs_office/ladder")
list_Add("OverrideMaterials", "models/cs_italy/blkmetal")
list_Add("OverrideMaterials", "models/cs_italy/light_orange")
list_Add("OverrideMaterials", "models/cs_italy/plaster")
list_Add("OverrideMaterials", "models/cs_italy/pwtrim2")
list_Add("OverrideMaterials", "models/props/de_inferno/clockwood01")
list_Add("OverrideMaterials", "cs_havana/rockgranite02a")
list_Add("OverrideMaterials", "models/props/de_nuke/railing_bombsitea")

--HL:S
if IsMounted("hl1") then
    list_Add("OverrideMaterials", "halflife/!c3a1bw00")
    list_Add("OverrideMaterials", "halflife/+0laser1fall")
    list_Add("OverrideMaterials", "halflife/+0laser1falla")
    list_Add("OverrideMaterials", "halflife/+0~generic78a")
    list_Add("OverrideMaterials", "halflife/+0~generic78b")
    list_Add("OverrideMaterials", "halflife/+0~generic78c")
    list_Add("OverrideMaterials", "halflife/+0~generic78d")
    list_Add("OverrideMaterials", "halflife/+0~generic85")
    list_Add("OverrideMaterials", "halflife/+0~generic86")
    list_Add("OverrideMaterials", "halflife/+0~generic86b")
    list_Add("OverrideMaterials", "halflife/+0~generic86r")
    list_Add("OverrideMaterials", "halflife/+a~generic78a")
    list_Add("OverrideMaterials", "halflife/+a~generic78b")
    list_Add("OverrideMaterials", "halflife/+a~generic78c")
    list_Add("OverrideMaterials", "halflife/+a~generic78d")
    list_Add("OverrideMaterials", "halflife/+a~generic85")
    list_Add("OverrideMaterials", "halflife/+a~generic86")
    list_Add("OverrideMaterials", "halflife/+a~generic86b")
    list_Add("OverrideMaterials", "halflife/+a~generic86r")
    list_Add("OverrideMaterials", "liquids/!greenslime")
    list_Add("OverrideMaterials", "liquids/!greenslime_1sided")
    list_Add("OverrideMaterials", "liquids/!greenslime_beneath")
    list_Add("OverrideMaterials", "liquids/water_risingblue")
    list_Add("OverrideMaterials", "liquids/water_rising")
    list_Add("OverrideMaterials", "liquids/toxic_anim")
    list_Add("OverrideMaterials", "models/concretegibs/concrete")
    list_Add("OverrideMaterials", "models/catwalkgibs/catwalk2")
    list_Add("OverrideMaterials", "models/sat_globe/topo")
    list_Add("OverrideMaterials", "xeno/crys_1a")
    list_Add("OverrideMaterials", "xeno/crys_1b")
    list_Add("OverrideMaterials", "xeno/crys_1c")
    list_Add("OverrideMaterials", "xeno/crys_1top")
    list_Add("OverrideMaterials", "xeno/crys_2a")
    list_Add("OverrideMaterials", "xeno/crys_2b")
    list_Add("OverrideMaterials", "xeno/crys_2top")
    list_Add("OverrideMaterials", "xeno/crys_3a")
    list_Add("OverrideMaterials", "xeno/crys_3b")
    list_Add("OverrideMaterials", "xeno/crys_3top")
    list_Add("OverrideMaterials", "xeno/crys_4a")
    list_Add("OverrideMaterials", "xeno/crys_4b")
end

--TF2
if IsMounted("tf") then
    list_Add("OverrideMaterials", "models/player/shared/gold_player")
    list_Add("OverrideMaterials", "models/player/shared/ice_player")
    list_Add("OverrideMaterials", "models/bots/bot_worker/bot_worker_powercore_blue")
    list_Add("OverrideMaterials", "models/bots/bot_worker/bot_worker_powercore_red")
    list_Add("OverrideMaterials", "models/bots/gameplay_cosmetic/bot_light")
    list_Add("OverrideMaterials", "models/bots/gameplay_cosmetic/bot_light_off")
    list_Add("OverrideMaterials", "models/bots/merasmus/eyeball_spectral")
    list_Add("OverrideMaterials", "models/buildables/dispenser/dispenser_screen")
    list_Add("OverrideMaterials", "models/buildables/sentry_shield/sentry_shield")
    list_Add("OverrideMaterials", "models/buildables/sentry_shield/sentry_shield_blue")
    list_Add("OverrideMaterials", "models/custom/pl_hoodoo/metaldoor001")
    list_Add("OverrideMaterials", "models/effects/resist_shield/mvm_resist_shield")
    list_Add("OverrideMaterials", "models/effects/resist_shield/mvm_vaccinator_shield_bullets")
    list_Add("OverrideMaterials", "models/effects/resist_shield/mvm_vaccinator_shield_explosives")
    list_Add("OverrideMaterials", "models/effects/resist_shield/mvm_vaccinator_shield_fire")
    list_Add("OverrideMaterials", "models/effects/resist_shield/resist_shield")
    list_Add("OverrideMaterials", "models/effects/resist_shield/resist_shield_blue")
    list_Add("OverrideMaterials", "models/items/crystal_ball_glass")
    list_Add("OverrideMaterials", "models/items/crystal_ball_glass_2")
    list_Add("OverrideMaterials", "models/items/australium_bar_blue")
    list_Add("OverrideMaterials", "models/items/australium_bar_red")
    list_Add("OverrideMaterials", "models/passtime/flasks/flask_glass")
    list_Add("OverrideMaterials", "models/passtime/turbine/goal_blu_glow")
    list_Add("OverrideMaterials", "models/passtime/turbine/goal_green_glow")
    list_Add("OverrideMaterials", "models/passtime/turbine/goal_grey_glow")
    list_Add("OverrideMaterials", "models/passtime/turbine/goal_red_glow")
    list_Add("OverrideMaterials", "models/passtime/tv/passtime_tv_screen_off")
    list_Add("OverrideMaterials", "models/props_barnblitz/concretefloor003")
    list_Add("OverrideMaterials", "models/props_barnblitz/woodwall_darkbrown001")
    list_Add("OverrideMaterials", "models/props_barnblitz/woodwall_darkbrown001b")
    list_Add("OverrideMaterials", "models/props_doomsday/australium_bar")
    list_Add("OverrideMaterials", "models/props_halloween/hwn_kart_ball01")
    list_Add("OverrideMaterials", "models/props_halloween/hwn_tent_pole01")
    list_Add("OverrideMaterials", "models/props_halloween/hwn_jump_hoop02")
    list_Add("OverrideMaterials", "models/props_halloween/hwn_jump_hoop01")
    list_Add("OverrideMaterials", "models/props_halloween/hwn_kart_track01")
    list_Add("OverrideMaterials", "models/props_halloween/hwn_bell_ringer_pole01")
    list_Add("OverrideMaterials", "models/props_harbor/rail_lines_harbor")
    list_Add("OverrideMaterials", "models/props_lakeside/flat_wall_02")
    list_Add("OverrideMaterials", "models/props_lakeside/flat_wall_03")
    list_Add("OverrideMaterials", "models/props_lakeside_event/wof_spiral")
    list_Add("OverrideMaterials", "models/props_lakeside_event/wof_card_glow")
    list_Add("OverrideMaterials", "models/props_mining/rock006")
    list_Add("OverrideMaterials", "models/props_mining/rock006a")
    list_Add("OverrideMaterials", "models/props_mining/rock006b")
    list_Add("OverrideMaterials", "models/props_moonbase/moon_interior_monitor01_text")
    list_Add("OverrideMaterials", "models/props_movies/kitteh/hamster")
    list_Add("OverrideMaterials", "models/props_movies/kitteh/kitteh")
    list_Add("OverrideMaterials", "models/props_movies/kitteh/puppy")
    list_Add("OverrideMaterials", "models/props_mvm/mvm_museum_coal")
    list_Add("OverrideMaterials", "models/props_mvm/mvm_revive_heavy")
    list_Add("OverrideMaterials", "models/props_mvm/hatchmetal")
    list_Add("OverrideMaterials", "models/props_mvm/blue_window002_glass")
    list_Add("OverrideMaterials", "models/props_mvm/museum_glass")
    list_Add("OverrideMaterials", "models/props_nightfall/wood_floor002")
    list_Add("OverrideMaterials", "models/props_nightfall/wood_bridge001")
    list_Add("OverrideMaterials", "models/props_skybox/computerwall007")
    list_Add("OverrideMaterials", "models/props_skybox/concretefloor002")
    list_Add("OverrideMaterials", "models/props_skybox/concretefloor007")
    list_Add("OverrideMaterials", "models/props_skybox/concretewall003")
    list_Add("OverrideMaterials", "models/props_skybox/concretewall007")
    list_Add("OverrideMaterials", "models/props_skybox/brickwall001")
    list_Add("OverrideMaterials", "models/props_skybox/ibeam001b")
    list_Add("OverrideMaterials", "models/props_sunshine/computerwall003")
    list_Add("OverrideMaterials", "models/props_sunshine/computerwall007")
    list_Add("OverrideMaterials", "models/props_sunshine/concretefloor003")
    list_Add("OverrideMaterials", "models/props_sunshine/wall029")
    list_Add("OverrideMaterials", "models/props_sunshine/concretewall011b")
    list_Add("OverrideMaterials", "models/props_sunshine/concretewall014")
    list_Add("OverrideMaterials", "models/props_sunshine/ibeam003")
    list_Add("OverrideMaterials", "models/props_sunshine/imetal003")
    list_Add("OverrideMaterials", "models/props_sunshine/metalstair001a")
    list_Add("OverrideMaterials", "models/props_swamp/rock006_swamp")
    list_Add("OverrideMaterials", "models/props_training/flashcard_base")
    list_Add("OverrideMaterials", "models/props_urban/brickwall003")
    list_Add("OverrideMaterials", "models/props_urban/brickwall005c")
    list_Add("OverrideMaterials", "models/props_urban/brickwall006")
    list_Add("OverrideMaterials", "models/props_vehicles/train_container")
    list_Add("OverrideMaterials", "models/props_vehicles/train_container_red")
    list_Add("OverrideMaterials", "models/props_vehicles/train_container_yellow")
    list_Add("OverrideMaterials", "models/props_viaduct_event/underworld_stumps01")
    list_Add("OverrideMaterials", "models/props_viaduct_event/underworld_sky01")
    list_Add("OverrideMaterials", "models/props_viaduct_event/door_glow_gradient")
    list_Add("OverrideMaterials", "models/props_viaduct_event/viaduct_cobblestone001")
    list_Add("OverrideMaterials", "models/vgui/computerwall003c_vgui")
    list_Add("OverrideMaterials", "models/vgui/concretewall011_vgui")
    list_Add("OverrideMaterials", "models/vgui/ibeam001b_vgui")
    list_Add("OverrideMaterials", "models/vgui/ibeam001_vgui")
    list_Add("OverrideMaterials", "models/vgui/class_wall")
    list_Add("OverrideMaterials", "models/vgui/class2_wall")
    list_Add("OverrideMaterials", "nature/underworld_lava001")
    list_Add("OverrideMaterials", "nature/moon_large")
    list_Add("OverrideMaterials", "passtime/neons/neon_blue_point")
    list_Add("OverrideMaterials", "passtime/neons/neon_blue_solid")
    list_Add("OverrideMaterials", "passtime/neons/neon_blue_stripe")
    list_Add("OverrideMaterials", "passtime/neons/neon_green_point")
    list_Add("OverrideMaterials", "passtime/neons/neon_green_solid")
    list_Add("OverrideMaterials", "passtime/neons/neon_green_stripe")
    list_Add("OverrideMaterials", "passtime/neons/neon_red_point")
    list_Add("OverrideMaterials", "passtime/neons/neon_red_solid")
    list_Add("OverrideMaterials", "passtime/neons/neon_red_stripe")
    list_Add("OverrideMaterials", "passtime/neons/neon_orange_point")
    list_Add("OverrideMaterials", "passtime/neons/neon_orange_solid")
    list_Add("OverrideMaterials", "passtime/neons/neon_orange_stripe")
    list_Add("OverrideMaterials", "passtime/neons/neon_yellow_point")
    list_Add("OverrideMaterials", "passtime/neons/neon_yellow_solid")
    list_Add("OverrideMaterials", "passtime/neons/neon_yellow_stripe")
    list_Add("OverrideMaterials", "dev/vr_bluegrid")
    list_Add("OverrideMaterials", "effects/beam_neutral")
    list_Add("OverrideMaterials", "glass/green_glass_opaque")
    list_Add("OverrideMaterials", "models/hybridphysx/concretefloor003")
    list_Add("OverrideMaterials", "models/lilchewchew/embers")
    list_Add("OverrideMaterials", "models/player/items/all_class/all_class_oculus_screen")
    list_Add("OverrideMaterials", "models/player/items/all_class/all_class_oculus_screen_blue")
    list_Add("OverrideMaterials", "models/player/items/all_class/chess_hologram_blue")
    list_Add("OverrideMaterials", "models/player/items/all_class/chess_hologram_red")
    list_Add("OverrideMaterials", "models/player/items/crafting/stat_clock_blue_happy")
    list_Add("OverrideMaterials", "models/player/items/crafting/stat_clock_blue_sad")
    list_Add("OverrideMaterials", "models/player/items/crafting/stat_clock_red_happy")
    list_Add("OverrideMaterials", "models/player/items/crafting/stat_clock_red_sad")
    list_Add("OverrideMaterials", "models/player/items/crafting/stat_clock_types")
    list_Add("OverrideMaterials", "models/player/items/heavy/xms_heavy_sandvichsafe_decal")
    list_Add("OverrideMaterials", "models/player/items/heavy/xms_heavy_sandvichsafe_decal_blue")
    list_Add("OverrideMaterials", "models/player/items/medic/qc_glove_secondary")
    list_Add("OverrideMaterials", "models/player/items/medic/qc_glove_secondary_blue")
    list_Add("OverrideMaterials", "models/player/items/scout/pep_bag_decal")
    list_Add("OverrideMaterials", "models/player/items/taunts/coffee")
    list_Add("OverrideMaterials", "models/props_2fort/building_farm01_wall")
    list_Add("OverrideMaterials", "models/props_2fort/fire_extinguisher_cabinet01_glass")
    list_Add("OverrideMaterials", "models/props_2fort/wood_bridge001")
    list_Add("OverrideMaterials", "models/props_2fort/wood_wall001")
    list_Add("OverrideMaterials", "models/props_doomsday/dirtground006")
    list_Add("OverrideMaterials", "models/props_forest/computerwall_blue_stained")
    list_Add("OverrideMaterials", "models/props_forest/computerwall_red_stained")
    list_Add("OverrideMaterials", "models/props_forest/concretefloor003")
    list_Add("OverrideMaterials", "models/props_forest/concretewall001e")
end

-- CSGO
--[[if IsMounted("csgo") then
    list_Add("OverrideMaterials", "buildings/office_wall_brick_edge")
    list_Add("OverrideMaterials", "coop_cementplant/mission_select_whitespace_blend")
    list_Add("OverrideMaterials", "coop_cementplant/mission_select_whitespacet")
    list_Add("OverrideMaterials", "cs_assault/windowbrightness")
    list_Add("OverrideMaterials", "de_dust/hr_dust/dust_ornament_overlay")
    list_Add("OverrideMaterials", "de_dust/hr_dust/hr_dust_sidewalk01_color")
    list_Add("OverrideMaterials", "de_nuke/hr_nuke/caustics_001")
    list_Add("OverrideMaterials", "effects/coopphoenixloadingscreen")
    list_Add("OverrideMaterials", "de_nuke/hr_nuke/caustics_001_decal")
    list_Add("OverrideMaterials", "de_vertigo/tv_blank")
    list_Add("OverrideMaterials", "de_vertigo/tv_noise")
    list_Add("OverrideMaterials", "dev/replay_you")
    list_Add("OverrideMaterials", "dust_massive/skybox_horizon_fade")
    list_Add("OverrideMaterials", "effects/digital_level_bar")
    list_Add("OverrideMaterials", "effects/slideshow_kasbah_01")
    list_Add("OverrideMaterials", "effects/slideshow_kasbah_02")
    list_Add("OverrideMaterials", "effects/slideshow_kasbah_03")
    list_Add("OverrideMaterials", "effects/slideshow_kasbah_04")
    list_Add("OverrideMaterials", "fx/bombsite_marker")
    list_Add("OverrideMaterials", "gg_tibet/cs_tibet_stone_06a")
    list_Add("OverrideMaterials", "hr_massive/skybox_horizon_fade")
    list_Add("OverrideMaterials", "hr_massive/town_plaster_2")
    list_Add("OverrideMaterials", "models/cs_italy/hangingflag")
    list_Add("OverrideMaterials", "models/cs_italy/light_orange2")
    list_Add("OverrideMaterials", "models/de_dust/objects/dust_walltop")
    list_Add("OverrideMaterials", "models/destruction_tanker/blackcable")
    list_Add("OverrideMaterials", "models/destruction_tanker/concrete_wall")
    list_Add("OverrideMaterials", "models/destruction_tanker/dmetal_ext_02")
    list_Add("OverrideMaterials", "models/destruction_tanker/dwoodceiling003a")
    list_Add("OverrideMaterials", "models/inventory_items/music_kit/mp3_screen_blank")
    list_Add("OverrideMaterials", "models/props/ar_dizzy/dizzy_drywall_stack/dizzy_drywall_stack_color")
    list_Add("OverrideMaterials", "models/props/ar_dizzy/dizzy_insulation/dizzy_insulation_bundle_wrap_color")
    list_Add("OverrideMaterials", "models/props/ar_dizzy/dizzy_trash/dizzy_cardboard_trash_color")
    list_Add("OverrideMaterials", "models/props/ar_dizzy/ibeams/dizzy_ibeams_color")
    list_Add("OverrideMaterials", "models/props/ar_lunacy/moon_bigdome/moon_bigdome_panels")
    list_Add("OverrideMaterials", "models/props/ar_lunacy/moon_buggy/moon_buggy_body")
    list_Add("OverrideMaterials", "models/props/ar_lunacy/moon_plantdome/moon_plantdome_glass")
    list_Add("OverrideMaterials", "models/props/ar_lunacy/moon_rocks/moon_rock_04_color")
    list_Add("OverrideMaterials", "models/props/ar_lunacy/moon_trims/trim_01_color")
    list_Add("OverrideMaterials", "models/props/ar_lunacy/rover/rover_glass_color")
    list_Add("OverrideMaterials", "models/props/coop_cementplant/coop_garage_door/coop_garage_door_glass_color")
    list_Add("OverrideMaterials", "models/props/coop_cementplant/coop_silo_ladder/coop_silo_ladder_color")
    list_Add("OverrideMaterials", "models/props/coop_cementplant/coop_wooden_pallet/coop_wooden_pallet_color")
    list_Add("OverrideMaterials", "models/props/coop_cementplant/phoenix/phoenix_flag_color")
    list_Add("OverrideMaterials", "models/props/coop_kashbah/bed_cloth_color")
    list_Add("OverrideMaterials", "models/props/coop_kashbah/instrument_table_cloth_color")
    list_Add("OverrideMaterials", "models/props/coop_kashbah/office_floor_tiles")
    list_Add("OverrideMaterials", "models/props/coop_kashbah/stop_sign/stop_sign")
    list_Add("OverrideMaterials", "models/props/cs_assault/box_solo")
    list_Add("OverrideMaterials", "models/props/cs_assault/car_tarp")
    list_Add("OverrideMaterials", "models/props/cs_assault/security_fence01")
    list_Add("OverrideMaterials", "models/props/cs_assault/security_fence02")
    list_Add("OverrideMaterials", "models/props/cs_assault/palletwood")
    list_Add("OverrideMaterials", "models/props/cs_italy/brick_arch01")
    list_Add("OverrideMaterials", "models/props/cs_italy/hpe_italy_pipe_wall")
    list_Add("OverrideMaterials", "models/props/cs_italy/italy_window_bars")
    list_Add("OverrideMaterials", "models/props/cs_italy/plaster")
    list_Add("OverrideMaterials", "models/props/cs_militia/rocka/rock_a_diffuse")
    list_Add("OverrideMaterials", "models/props/cs_militia/rockb/rock_b_diffuse")
    list_Add("OverrideMaterials", "models/props/cs_office/bankglass")
    list_Add("OverrideMaterials", "models/props/de_aztec/aztec_big_stairs")
    list_Add("OverrideMaterials", "models/props/de_aztec/aztec_big_stairs_side")
    list_Add("OverrideMaterials", "models/props/de_aztec/hpe_aztec_stone01")
    list_Add("OverrideMaterials", "models/props/de_aztec/trim64b")
    list_Add("OverrideMaterials", "models/props/de_cbble/arch_a")
    list_Add("OverrideMaterials", "models/props/de_cbble/arch_c")
    list_Add("OverrideMaterials", "models/props/de_cbble/corner_trim_a/brick_a")
    list_Add("OverrideMaterials", "models/props/de_cbble/corner_trim_a/brick_a_corner_stone")
    list_Add("OverrideMaterials", "models/props/de_cbble/corner_trim_c/brick_a_corner_stone_stain")
    list_Add("OverrideMaterials", "models/props/de_cbble/knight_armour/knight_armour_chainmail")
    list_Add("OverrideMaterials", "models/props/de_cbble/old_weapons/old_weapons")
    list_Add("OverrideMaterials", "models/props/de_cbble/pine_a/pine_a_bark")
    list_Add("OverrideMaterials", "models/props/de_cbble/roof_top_a/brick_b_plaster")
    list_Add("OverrideMaterials", "models/props/de_cbble/tent_a/tent_a")
    list_Add("OverrideMaterials", "models/props/de_cbble/tent_a/tent_a_metal")
    list_Add("OverrideMaterials", "models/props/de_cbble/tent_a/tent_a_tarp")
    list_Add("OverrideMaterials", "models/props/de_cbble/tent_a/tent_a_wood_a")
    list_Add("OverrideMaterials", "models/props/de_cbble/tent_a/tent_a_wood_shutter")
    list_Add("OverrideMaterials", "models/props/de_cbble/tent_a/tent_a_wood_siding")
    list_Add("OverrideMaterials", "models/props/de_cbble/wall_detail_b/wall_detail_b")
    list_Add("OverrideMaterials", "models/props/de_cbble/wall_trim_b/wall_trim_b")
    list_Add("OverrideMaterials", "models/props/de_dust/rebar")
    list_Add("OverrideMaterials", "models/props/de_dust/rock_tint")
    list_Add("OverrideMaterials", "models/props/de_dust/rug01")
    list_Add("OverrideMaterials", "models/props/de_dust/rug02")
    list_Add("OverrideMaterials", "models/props/de_dust/rug03")
    list_Add("OverrideMaterials", "models/props/de_dust/rug04")
    list_Add("OverrideMaterials", "models/props/de_dust/rug05")
    list_Add("OverrideMaterials", "models/props/de_dust/rug06")
    list_Add("OverrideMaterials", "models/props/de_dust/skybox_dust_hotel01")
    list_Add("OverrideMaterials", "models/props/de_dust/skybox_dust_hotel02")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_arches/dust_arch_01")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_curbs_001/dust_curbs_001")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_curbs_001/dust_curbs_001_painted")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_electric_panel/dust_electric_panel_cover_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_fences/dust_chainlink_fence_cover_001")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_fences/dust_chainlink_fence_wire_001")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_kasbah_flat_stones")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_kasbah_mudbrick_single")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_kasbah_rock_wall")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_mudbrick_bombsite_gap")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_mudbrick_crumbling_wall")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_mudbrick_edges")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_mudbrick_plaster")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_mudbrick_tower_01_edges")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_kasbah/dust_mudbrick_tower_01_plaster")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_manholes/dust_manhole_01_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_manholes/dust_manhole_02_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_manholes/dust_manhole_03_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_metal_panels/dust_metal_panels_01")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_metal_panels/dust_metal_panels_rusty_01")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_rooftops/dust_rooftop_shingles_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_skybox/hr_dust_ground_sand_skybox")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_skybox/hr_dust_skybox_buildings_01")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_soccerball/soccer_goal_chainlink_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_trims/hr_dust_sidewalk01b_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_vehicles/dust_vehicle_glass_color")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/dust_wood_pallet/dust_wood_pallet")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/foliage/olive_bark_01")
    list_Add("OverrideMaterials", "models/props/de_dust/hr_dust/wooden_structures/wooden_structure_2")
    list_Add("OverrideMaterials", "models/props/de_house/wall_house01")
    list_Add("OverrideMaterials", "models/props/de_inferno/hazard_ribbons")
    list_Add("OverrideMaterials", "models/props/de_inferno/hpe_italy_stone_wall_02")
    list_Add("OverrideMaterials", "models/props/de_inferno/hpe_stone_wall_02")
    list_Add("OverrideMaterials", "models/props/de_inferno/infwllf")
    list_Add("OverrideMaterials", "models/props/de_inferno/infwllh")
    list_Add("OverrideMaterials", "models/props/de_inferno/infwlli")
    list_Add("OverrideMaterials", "models/props/de_inferno/infwllj")
    list_Add("OverrideMaterials", "models/props/de_inferno/infwlll")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/arch_a/brick_d1")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/arch_d/brick_m")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/arch_e/concrete_b")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/bench/bench")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/chimney/roofing_tile_a")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/church_bricks/church_bricks")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/church_pillar/church_pillar_a_base")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/curb_a/concrete_b")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/cypress_a/bark")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/door_collection/hr_wood_planks_a")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/electric_box_a/electric_box_a")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/fountain_a/fountain_a_water")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/fountain_a_basin/tiles_a2")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/ground_stone/ground_stone")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/ground_tile_a/herringbone_b")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/hay_bale/hay_bale")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/inferno_building_skybox/inferno_building_skybox_plaster")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/inferno_folding_shutters/inferno_folding_shutters_illum")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/ivy_a/ivy_bark_a")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/lattice_a/lattice_a")
    list_Add("OverrideMaterials", "models/props/de_inferno/hr_i/pillar_b/pillar_b_white")
    list_Add("OverrideMaterials", "models/props/de_mill/sugarcane")
    list_Add("OverrideMaterials", "models/props/de_mirage/brush_shapes/sitebwall13a")
    list_Add("OverrideMaterials", "models/props/de_mirage/wall_hole/sheet_metal_panel")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/chainlink_fence_001/chainlink_fence_cover_001")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/chainlink_fence_001/chainlink_fence_wire_001")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/foliage/beech_bark_01")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/foliage/cedar_bark_01")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/metal_door_001/metal_door_001_glass")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/nuke_columns/hr_concrete_wall_painted_001_color")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/nuke_industrial_props/hr_concrete_column_001_color")
    list_Add("OverrideMaterials", "models/props/de_nuke/hr_nuke/nuke_industrial_props/hr_metal_duct_001_color")
    list_Add("OverrideMaterials", "models/props/de_overpass/cafe_display_glass_color")
    list_Add("OverrideMaterials", "models/props/de_train/hr_t/fan_a/metal_grated_d")
    list_Add("OverrideMaterials", "models/props/de_train/hr_t/floor_bumper_a/hr_metal_wall_c")
    list_Add("OverrideMaterials", "models/props/de_train/hr_t/nuclear_container_a/nuclear_container_symbol")
    list_Add("OverrideMaterials", "models/props/de_train/hr_t/pigeon_sign/pigeon_sign")
    list_Add("OverrideMaterials", "models/props/de_train/hr_t/tiles_a_broken/tiles_a2")
    list_Add("OverrideMaterials", "models/props/de_venice/doge_wainscoting_1/doge_wainscoting_1")
    list_Add("OverrideMaterials", "models/props/de_vertigo/insulationroll_pallet_plastic01")
    list_Add("OverrideMaterials", "models/props/de_vertigo/metal_rendered")
    list_Add("OverrideMaterials", "models/props/de_vertigo/trafficcone_clean")
    list_Add("OverrideMaterials", "models/props/de_vertigo/vertigo_concretefloor_prop")
    list_Add("OverrideMaterials", "models/props/de_vertigo/construction_elevator/construction_elevator_chain")
    list_Add("OverrideMaterials", "models/props/de_vostok/woodrailingsbreakable")
    list_Add("OverrideMaterials", "models/props/dust_massive/beachwaves_dust/beachwaves_dust")
    list_Add("OverrideMaterials", "models/props/dust_massive/debris/dust_broken_roof")
    list_Add("OverrideMaterials", "models/props/dust_massive/roof/military_base_roof_01")
    list_Add("OverrideMaterials", "models/props/gg_handling/baggage_track_rails")
    list_Add("OverrideMaterials", "models/props/gg_handling/metal_flat")
    list_Add("OverrideMaterials", "models/props/gg_tibet/candlestick")
    list_Add("OverrideMaterials", "models/props/gg_tibet/cs_tibet_plaster_01")
    list_Add("OverrideMaterials", "models/props/gg_tibet/cs_tibet_stone_06")
    list_Add("OverrideMaterials", "models/props/gg_tibet/cs_tibet_stone_07a")
    list_Add("OverrideMaterials", "models/props/gg_tibet/infwllc")
    list_Add("OverrideMaterials", "models/props/gg_tibet/snow")
    list_Add("OverrideMaterials", "models/props/gg_tibet/stone_wall")
    list_Add("OverrideMaterials", "models/props/gg_tibet/stupa_small01")
    list_Add("OverrideMaterials", "models/props/gg_tibet/stupa_small02")
    list_Add("OverrideMaterials", "models/props/gg_tibet/tibet_prayerflag_rope")
    list_Add("OverrideMaterials", "models/props/gg_tibet/vostok_plaster03")
    list_Add("OverrideMaterials", "models/props/gg_tibet/wllv01")
    list_Add("OverrideMaterials", "models/props/gg_vietnam/bamboostalk")
    list_Add("OverrideMaterials", "models/props/gg_vietnam/gg_vietnam_platform_slats_ct")
    list_Add("OverrideMaterials", "models/props/gg_vietnam/gg_vietnam_platform_slats_t")
    list_Add("OverrideMaterials", "models/props/gg_vietnam/vietnam_corrugated_01")
    list_Add("OverrideMaterials", "models/props/holiday_light/holiday_light")
    list_Add("OverrideMaterials", "models/props/hr_massive/beach_rock_1/beach_rock_1")
    list_Add("OverrideMaterials", "models/props/hr_vertigo/metal_rebar/metal_rebar")
    list_Add("OverrideMaterials", "models/props/hr_vertigo/traffic_cone/vertigo_traffic_cone_color")
    list_Add("OverrideMaterials", "models/props/hr_vertigo/vertigo_plastic_pipes/vertigo_plastic_pipes_color")
    list_Add("OverrideMaterials", "models/props/hr_vertigo/vertigo_railing_platform/vertigo_railing_platform_color")
    list_Add("OverrideMaterials", "models/props/hr_vertigo/vertigo_scaffolding/vertigo_scaffolding_tarp_color")
    list_Add("OverrideMaterials", "models/props/hr_vertigo/vertigo_tarp/tarp_01_color")
    list_Add("OverrideMaterials", "models/props/props_gameplay/prop_bomb_blast_wall")
    list_Add("OverrideMaterials", "models/props_farm/chicken_bday_hat")
    list_Add("OverrideMaterials", "models/props_highway/metal_corrugated03b")
    list_Add("OverrideMaterials", "models/props_highway/overpass_1")
    list_Add("OverrideMaterials", "models/props_highway/plywood_ext_01")
    list_Add("OverrideMaterials", "models/props_survival/dronegun/dronegun_laser")
    list_Add("OverrideMaterials", "models/props_survival/safe/safe_explosives_lights")
    list_Add("OverrideMaterials", "windows/hr_w/inferno/stained_glass_a_selfillum")
end--]]

--Misc
list_Add("OverrideMaterials", "engine/singlecolor")
list_Add("OverrideMaterials", "models/nihilanth/chrome_nihilanth")
list_Add("OverrideMaterials", "models/islave/chrome_1")
list_Add("OverrideMaterials", "squad/orangebox")
list_Add("OverrideMaterials", "hunter/mywindow")
list_Add("OverrideMaterials", "hlmv/floor")
list_Add("OverrideMaterials", "gmod/edit_fog")
list_Add("OverrideMaterials", "gmod/edit_sky")
list_Add("OverrideMaterials", "gmod/edit_sun")

--XQM
list_Add("OverrideMaterials", "models/xqm/lightlinesred")
list_Add("OverrideMaterials", "models/xqm/lightlinesred_tool")
list_Add("OverrideMaterials", "models/xqm/woodtexture_1")
list_Add("OverrideMaterials", "models/xqm/woodplanktexture")
list_Add("OverrideMaterials", "models/xqm/polex1_diffuse")
list_Add("OverrideMaterials", "models/xqm/lightlinesgb")
list_Add("OverrideMaterials", "models/xqm/deg360")
list_Add("OverrideMaterials", "models/xqm/cylinderx1_diffuse")
list_Add("OverrideMaterials", "models/xqm/cinderblock_tex")
list_Add("OverrideMaterials", "models/xqm/cellshadedcamo_diffuse")
list_Add("OverrideMaterials", "models/xqm/2deg360_diffuse")
list_Add("OverrideMaterials", "models/xqm/boxfull_diffuse")

----

-- ColorMater lists
--Default ones so we can list them with out any others that may have added
list_Add("OverrideMaterials", "models/wireframe")
list_Add("OverrideMaterials", "debug/env_cubemap_model")
list_Add("OverrideMaterials", "models/shadertest/shader3")
list_Add("OverrideMaterials", "models/shadertest/shader4")
list_Add("OverrideMaterials", "models/shadertest/shader5")
list_Add("OverrideMaterials", "models/shiny")
list_Add("OverrideMaterials", "models/debug/debugwhite")
list_Add("OverrideMaterials", "Models/effects/comball_sphere")
list_Add("OverrideMaterials", "Models/effects/comball_tape")
list_Add("OverrideMaterials", "Models/effects/vol_light001")
list_Add("OverrideMaterials", "models/props_combine/stasisshield_sheet")
list_Add("OverrideMaterials", "models/props_combine/portalball001_sheet")
list_Add("OverrideMaterials", "models/props_combine/com_shield001a")
list_Add("OverrideMaterials", "models/props_c17/frostedglass_01a")
list_Add("OverrideMaterials", "models/props_lab/Tank_Glass001")
list_Add("OverrideMaterials", "models/props_combine/tprings_globe")
list_Add("OverrideMaterials", "models/rendertarget")
list_Add("OverrideMaterials", "models/screenspace")
list_Add("OverrideMaterials", "brick/brick_model")
list_Add("OverrideMaterials", "models/props_foliage/tree_deciduous_01a_trunk")

--Extra Materials 3.0
list_Add("OverrideMaterials", "models/props_pipes/pipeset_metal02")
list_Add("OverrideMaterials", "models/props_pipes/pipeset_metal")
list_Add("OverrideMaterials", "models/props_combine/tprotato1_sheet")
list_Add("OverrideMaterials", "models/combine_advisor/body9")
list_Add("OverrideMaterials", "models/props_debris/building_template012d")
list_Add("OverrideMaterials", "models/props_combine/tprings_sheet")
list_Add("OverrideMaterials", "models/props_wasteland/lighthouse_stairs")
list_Add("OverrideMaterials", "models/props_c17/frostedglass_01a_dx60")
list_Add("OverrideMaterials", "models/vortigaunt/pupil")

--PHX Materials
list_Add("OverrideMaterials", "phoenix_storms/Airboat")
list_Add("OverrideMaterials", "phoenix_storms/Blue_steel")
list_Add("OverrideMaterials", "phoenix_storms/FuturisticTrackRamp_1-2")
list_Add("OverrideMaterials", "phoenix_storms/Indenttiles2")
list_Add("OverrideMaterials", "phoenix_storms/Indenttiles_1-2")
list_Add("OverrideMaterials", "phoenix_storms/MetalSet_1-2")
list_Add("OverrideMaterials", "phoenix_storms/Metalfloor_2-3")
list_Add("OverrideMaterials", "phoenix_storms/OfficeWindow_1-1")
list_Add("OverrideMaterials", "phoenix_storms/airboat_blur02")
list_Add("OverrideMaterials", "phoenix_storms/amraam")
list_Add("OverrideMaterials", "phoenix_storms/barrel")
list_Add("OverrideMaterials", "phoenix_storms/barrel_fps")
list_Add("OverrideMaterials", "phoenix_storms/black_chrome")
list_Add("OverrideMaterials", "phoenix_storms/bluemetal")
list_Add("OverrideMaterials", "phoenix_storms/bomb")
list_Add("OverrideMaterials", "phoenix_storms/camera")
list_Add("OverrideMaterials", "phoenix_storms/cannon")
list_Add("OverrideMaterials", "phoenix_storms/car_tire")
list_Add("OverrideMaterials", "phoenix_storms/chrome")
list_Add("OverrideMaterials", "phoenix_storms/cigar")
list_Add("OverrideMaterials", "phoenix_storms/cube")
list_Add("OverrideMaterials", "phoenix_storms/dome")
list_Add("OverrideMaterials", "phoenix_storms/dome_side")
list_Add("OverrideMaterials", "phoenix_storms/egg")
list_Add("OverrideMaterials", "phoenix_storms/explo_barrel")
list_Add("OverrideMaterials", "phoenix_storms/fender")
list_Add("OverrideMaterials", "phoenix_storms/fender_chrome")
list_Add("OverrideMaterials", "phoenix_storms/fender_white")
list_Add("OverrideMaterials", "phoenix_storms/fender_wood")
list_Add("OverrideMaterials", "phoenix_storms/future_vents")
list_Add("OverrideMaterials", "phoenix_storms/gear")
list_Add("OverrideMaterials", "phoenix_storms/gear_top")
list_Add("OverrideMaterials", "phoenix_storms/glass")
list_Add("OverrideMaterials", "phoenix_storms/grey_chrome")
list_Add("OverrideMaterials", "phoenix_storms/grey_steel")
list_Add("OverrideMaterials", "phoenix_storms/heli")
list_Add("OverrideMaterials", "phoenix_storms/iron_rails")
list_Add("OverrideMaterials", "phoenix_storms/lag_sign")
list_Add("OverrideMaterials", "phoenix_storms/metal")
list_Add("OverrideMaterials", "phoenix_storms/metal_plate")
list_Add("OverrideMaterials", "phoenix_storms/metal_wheel")
list_Add("OverrideMaterials", "phoenix_storms/metalbox")
list_Add("OverrideMaterials", "phoenix_storms/metalbox2")
list_Add("OverrideMaterials", "phoenix_storms/metalfence004a")
list_Add("OverrideMaterials", "phoenix_storms/middle")
list_Add("OverrideMaterials", "phoenix_storms/mrref2")
list_Add("OverrideMaterials", "phoenix_storms/mrtire")
list_Add("OverrideMaterials", "phoenix_storms/output_jack")
list_Add("OverrideMaterials", "phoenix_storms/plastic")
list_Add("OverrideMaterials", "phoenix_storms/point1")
list_Add("OverrideMaterials", "phoenix_storms/pack2/black")
list_Add("OverrideMaterials", "phoenix_storms/pack2/bluelight")
list_Add("OverrideMaterials", "phoenix_storms/pack2/chrome")
list_Add("OverrideMaterials", "phoenix_storms/pack2/darkblue")
list_Add("OverrideMaterials", "phoenix_storms/pack2/darkgrey")
list_Add("OverrideMaterials", "phoenix_storms/pack2/glass")
list_Add("OverrideMaterials", "phoenix_storms/pack2/interior_sides")
list_Add("OverrideMaterials", "phoenix_storms/pack2/interior_top")
list_Add("OverrideMaterials", "phoenix_storms/pack2/metalbox2")
list_Add("OverrideMaterials", "phoenix_storms/pack2/panel")
list_Add("OverrideMaterials", "phoenix_storms/pack2/redlight")
list_Add("OverrideMaterials", "phoenix_storms/pack2/train_floor")
list_Add("OverrideMaterials", "phoenix_storms/wood")
list_Add("OverrideMaterials", "phoenix_storms/stripes")
list_Add("OverrideMaterials", "phoenix_storms/wire/pcb_green")
list_Add("OverrideMaterials", "phoenix_storms/wire/pcb_red")
list_Add("OverrideMaterials", "phoenix_storms/wire/pcb_blue")

list_Add("OverrideMaterials", "hunter/myplastic")

--Even more materials from Material EX
--HL2
list_Add("OverrideMaterials", "models/items/boxsniperrounds")
list_Add("OverrideMaterials", "models/props_combine/pipes03")
list_Add("OverrideMaterials", "models/weapons/v_slam/new light1")

--Counter-Strike Source
list_Add("OverrideMaterials", "models/props/cs_assault/dollar")
list_Add("OverrideMaterials", "models/props/cs_assault/fireescapefloor")
list_Add("OverrideMaterials", "models/props/cs_assault/metal_stairs1")
list_Add("OverrideMaterials", "models/props/cs_assault/moneywrap")
list_Add("OverrideMaterials", "models/props/cs_assault/moneywrap02")
list_Add("OverrideMaterials", "models/props/cs_assault/moneytop")
list_Add("OverrideMaterials", "models/props/cs_assault/pylon")
list_Add("OverrideMaterials", "models/props/CS_militia/boulder01")
list_Add("OverrideMaterials", "models/props/CS_militia/milceil001")
list_Add("OverrideMaterials", "models/props/CS_militia/militiarock")
list_Add("OverrideMaterials", "models/props/CS_militia/militiarockb")
list_Add("OverrideMaterials", "models/props/CS_militia/milwall006")
list_Add("OverrideMaterials", "models/props/CS_militia/rocks01")
list_Add("OverrideMaterials", "models/props/CS_militia/roofbeams01")
list_Add("OverrideMaterials", "models/props/CS_militia/roofbeams02")
list_Add("OverrideMaterials", "models/props/CS_militia/roofbeams03")
list_Add("OverrideMaterials", "models/props/CS_militia/RoofEdges")
list_Add("OverrideMaterials", "models/props/cs_office/clouds")
list_Add("OverrideMaterials", "models/props/cs_office/file_cabinet2")
list_Add("OverrideMaterials", "models/props/cs_office/file_cabinet3")
list_Add("OverrideMaterials", "models/props/cs_office/screen")
list_Add("OverrideMaterials", "models/props/cs_office/snowmana")
list_Add("OverrideMaterials", "models/props/de_inferno/de_inferno_boulder_03")
list_Add("OverrideMaterials", "models/props/de_inferno/infflra")
list_Add("OverrideMaterials", "models/props/de_inferno/infflrd")
list_Add("OverrideMaterials", "models/props/de_inferno/inftowertop")
list_Add("OverrideMaterials", "models/props/de_inferno/offwndwb_break")
list_Add("OverrideMaterials", "models/props/de_inferno/roofbits")
list_Add("OverrideMaterials", "models/props/de_inferno/tileroof01")
list_Add("OverrideMaterials", "models/props/de_inferno/woodfloor008a")
list_Add("OverrideMaterials", "models/props/de_nuke/nukconcretewalla")
list_Add("OverrideMaterials", "models/props/de_nuke/nukecardboard")

--some more
--COMBINE
list_Add("OverrideMaterials", "models/props_combine/tpballglow")
list_Add("OverrideMaterials", "models/props_combine/combine_door01_glass")
list_Add("OverrideMaterials", "models/props_combine/combine_fenceglow")
list_Add("OverrideMaterials", "models/props_combine/weaponstripper_sheet")

--STUFF
list_Add("OverrideMaterials", "models/dav0r/hoverball")
list_Add("OverrideMaterials", "models/Items/boxart1")
list_Add("OverrideMaterials", "models/props/de_tides/clouds")
list_Add("OverrideMaterials", "models/props_c17/fisheyelens")
list_Add("OverrideMaterials", "models/props/cs_office/offinspa")
list_Add("OverrideMaterials", "models/props/cs_office/offinspb")
list_Add("OverrideMaterials", "models/props/cs_office/offinspc")
list_Add("OverrideMaterials", "models/props/cs_office/offinspd")
list_Add("OverrideMaterials", "models/props/cs_office/offinspf")
list_Add("OverrideMaterials", "models/props/cs_office/offinspg")
list_Add("OverrideMaterials", "models/balloon/balloon_hl2")
list_Add("OverrideMaterials", "models/balloon/balloon_nips")
list_Add("OverrideMaterials", "models/balloon/balloon_milfman")

-- SProps
if file.Exists("materials/sprops/sprops_grid_12x12.vmt","GAME") then
    list_Add("OverrideMaterials", "sprops/sprops_grid")
    list_Add("OverrideMaterials", "sprops/sprops_grid_12x12")
    list_Add("OverrideMaterials", "sprops/sprops_grid_b")
    list_Add("OverrideMaterials", "sprops/sprops_grid_dark_orange")
    list_Add("OverrideMaterials", "sprops/sprops_grid_orange")
    list_Add("OverrideMaterials", "sprops/sprops_grid_orange_12x12")
    list_Add("OverrideMaterials", "sprops/sprops_grid_orange_b")
    list_Add("OverrideMaterials", "sprops/sprops_plastic")

    list_Add("OverrideMaterials", "sprops/textures/exh_inner")
    list_Add("OverrideMaterials", "sprops/textures/gear_metal")
    list_Add("OverrideMaterials", "sprops/textures/hex_dark_bump")
    list_Add("OverrideMaterials", "sprops/textures/hex_dark_refl")
    list_Add("OverrideMaterials", "sprops/textures/hex_light_bump")
    list_Add("OverrideMaterials", "sprops/textures/hex_light_refl")
    list_Add("OverrideMaterials", "sprops/textures/sprops_cfiber1")
    list_Add("OverrideMaterials", "sprops/textures/sprops_cfiber2")
    list_Add("OverrideMaterials", "sprops/textures/sprops_chrome")
    list_Add("OverrideMaterials", "sprops/textures/sprops_chrome2")
    list_Add("OverrideMaterials", "sprops/textures/sprops_metal1")
    list_Add("OverrideMaterials", "sprops/textures/sprops_metal2")
    list_Add("OverrideMaterials", "sprops/textures/sprops_metal3")
    list_Add("OverrideMaterials", "sprops/textures/sprops_metal4")
    list_Add("OverrideMaterials", "sprops/textures/sprops_metal5")
    list_Add("OverrideMaterials", "sprops/textures/sprops_metal6")
    list_Add("OverrideMaterials", "sprops/textures/sprops_rubber")
    list_Add("OverrideMaterials", "sprops/textures/sprops_rubber2")
    list_Add("OverrideMaterials", "sprops/textures/sprops_wood1")
    list_Add("OverrideMaterials", "sprops/textures/sprops_wood2")
    list_Add("OverrideMaterials", "sprops/textures/sprops_wood3")
    list_Add("OverrideMaterials", "sprops/textures/sprops_wood4")

    list_Add("OverrideMaterials", "sprops/trans/lights/light_cover_b")
    list_Add("OverrideMaterials", "sprops/trans/lights/light_glass_b")
    list_Add("OverrideMaterials", "sprops/trans/lights/light_plastic")

    list_Add("OverrideMaterials", "sprops/trans/misc/beam_side")
    list_Add("OverrideMaterials", "sprops/trans/misc/beam_top")
    list_Add("OverrideMaterials", "sprops/trans/misc/g_glass")
    list_Add("OverrideMaterials", "sprops/trans/misc/ls_m1")
    list_Add("OverrideMaterials", "sprops/trans/misc/ls_m2")
    list_Add("OverrideMaterials", "sprops/trans/misc/sh_m1")
    list_Add("OverrideMaterials", "sprops/trans/misc/sh_m2")
    list_Add("OverrideMaterials", "sprops/trans/misc/tracks_wood")
    list_Add("OverrideMaterials", "sprops/trans/misc/train_metal1")
    list_Add("OverrideMaterials", "sprops/trans/misc/train_metal2")
    list_Add("OverrideMaterials", "sprops/trans/misc/train_metal3")
    list_Add("OverrideMaterials", "sprops/trans/misc/train_metal4")
    list_Add("OverrideMaterials", "sprops/trans/misc/train_metal5")

    list_Add("OverrideMaterials", "sprops/trans/wheels/wheel_d_rim1")
    list_Add("OverrideMaterials", "sprops/trans/wheels/wheel_d_rim2")
end

----

-- Deduplicate materials
hook.Add("PostGamemodeLoaded", "DeduplicateMaterials", function()
    local _ourMaterials = table.Copy(ourMaterials)
    ourMaterials = table.GetKeys(ourMaterials)
    Msg("[Stools] ") print("Previous material count:", prevCount)
    Msg("[Stools] ") print(Format("Adding %d materials...", #ourMaterials))

    local matList = list.GetForEdit("OverrideMaterials")
    local toReplace = {}

    Msg("[Stools] ") print("Condensing down materials...")
    Msg("[Stools] ") print("Materials before:", #matList)
    Msg("[Stools] ") print("Deduplicating...")

    for i, mat in ipairs(matList) do
        local sanitized = sanitize(mat)

        if toReplace[sanitized] then
            matList[i] = nil
            continue
        end

        toReplace[sanitized] = true
        matList[i] = nil
    end

    toReplace = table.GetKeys(toReplace)
    table.sort(toReplace)

    Msg("[Stools] ") print("Materials after:", #toReplace)
    Msg("[Stools] ") print("Materials other addons have added:", #toReplace - #ourMaterials)

    for i, mat in ipairs(toReplace) do
        matList[i] = mat
    end

    local added = {}
    for i, mat in ipairs(matList) do
        if not _ourMaterials[mat] then
            added[mat:lower()] = true
        end
    end

    concommand.Add("material_supercut_listadded", function()
        for mat in pairs(added) do
            print(mat)
        end
    end)
end)

----

--More Trails
list.Set("trail_materials", "bluelaser1", "effects/bluelaser1")
list.Set("trail_materials", "Yellow And Black", "sprites/combineball_trail_black_1")
list.Set("trail_materials", "Blue Laser", "sprites/combineball_trail_blue_1")
list.Set("trail_materials", "Red Laser ", "sprites/combineball_trail_red_1")
list.Set("trail_materials", "Crystal Beam", "cable/crystal_beam1")
list.Set("trail_materials", "Hydra Gut", "effects/hydragutbeam")

if IsMounted("episodic") then
    list.Set("trail_materials", "Hacked Rollermine", "sprites/yellowlaser1")
end

if IsMounted("tf") then
    list.Set("trail_materials", "Baseball (BLU)", "effects/baseballtrail_blu")
    list.Set("trail_materials", "Baseball (RED)", "effects/baseballtrail_red")
    list.Set("trail_materials", "Invulnerability Beam (BLU)", "effects/beam001_blu")
    list.Set("trail_materials", "Invulnerability Beam (RED)", "effects/beam001_red")
    list.Set("trail_materials", "Beam (BLU)", "effects/beam001_blu_dx80")
    list.Set("trail_materials", "Beam (RED)", "effects/beam001_red_dx80")
    list.Set("trail_materials", "Flag Trail (BLU)", "effects/flagtrail_blu")
    list.Set("trail_materials", "Flag Trail (RED)", "effects/flagtrail_red")
end

--More Ropes
list.Set("RopeMaterials", "Cable (alt)", "cable/cable_lit")

if IsMounted("ep2") then
    list.Set("RopeMaterials", "Metal Winch", "cable/cable_metalwinch01")
    list.Set("RopeMaterials", "Black Hose", "cable/hose_black1")
    list.Set("RopeMaterials", "Orange Hose", "cable/hose_orange1")
end

if IsMounted("csgo") then
    list.Set("RopeMaterials", "Cable (Nuke)", "cable/nuke_cable")
    list.Set("RopeMaterials", "Phone Cable", "cable/phonecable")
    list.Set("RopeMaterials", "Phone Cable (alt)", "cable/phonecable_red")
    list.Set("RopeMaterials", "Police Line", "cable/policeline")
    list.Set("RopeMaterials", "Police Line (german)", "cable/policeline_german")
    list.Set("RopeMaterials", "Rope (alt)", "cable/rope2")
    list.Set("RopeMaterials", "Yellow", "cable/yellow")
end

if IsMounted("tf") then
    list.Set("RopeMaterials", "Blue Cable", "cable/cable_blue")
    list.Set("RopeMaterials", "Red Cable", "cable/cable_red")
end

-- Add ropes as trails
list.Set("trail_materials", "#ropematerial.xbeam", "cable/xbeam")
list.Set("trail_materials", "#ropematerial.laser", "cable/redlaser")
list.Set("trail_materials", "#ropematerial.electric", "cable/blue_elec")
list.Set("trail_materials", "#ropematerial.physbeam", "cable/physbeam")
list.Set("trail_materials", "#ropematerial.hydra", "cable/hydra")

-- Add trails as ropes
local trailMats = list.Get("trail_materials")

for name, mat in pairs(trailMats) do
    list.Set("RopeMaterials", name, mat)
end